# Generated by Django 4.2.21 on 2025-05-30 07:02

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Offizieller Name des raumbezogenen Plans', max_length=2048, verbose_name='Name des Plans')),
                ('nummer', models.CharField(max_length=5, verbose_name='Nummer des Plans.')),
                ('geltungsbereich', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Grenze des räumlichen Geltungsbereiches des Plans.')),
                ('planart', models.CharField(choices=[('1000', 'BPlan'), ('10000', 'EinfacherBPlan'), ('10001', 'QualifizierterBPlan'), ('10002', 'BebauungsplanZurWohnraumversorgung'), ('3000', 'VorhabenbezogenerBPlan'), ('3100', 'VorhabenUndErschliessungsplan'), ('4000', 'InnenbereichsSatzung'), ('40000', 'KlarstellungsSatzung'), ('40001', 'EntwicklungsSatzung'), ('40002', 'ErgaenzungsSatzung'), ('5000', 'AussenbereichsSatzung'), ('7000', 'OertlicheBauvorschrift'), ('9999', 'Sonstiges')], db_index=True, default='1000', max_length=5, verbose_name='Typ des vorliegenden Bebauungsplans.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gemeinde', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.administrativeorganization')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical b plan',
                'verbose_name_plural': 'historical b plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Offizieller Name des raumbezogenen Plans', max_length=2048, verbose_name='Name des Plans')),
                ('nummer', models.CharField(max_length=5, verbose_name='Nummer des Plans.')),
                ('geltungsbereich', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Grenze des räumlichen Geltungsbereiches des Plans.')),
                ('planart', models.CharField(choices=[('1000', 'BPlan'), ('10000', 'EinfacherBPlan'), ('10001', 'QualifizierterBPlan'), ('10002', 'BebauungsplanZurWohnraumversorgung'), ('3000', 'VorhabenbezogenerBPlan'), ('3100', 'VorhabenUndErschliessungsplan'), ('4000', 'InnenbereichsSatzung'), ('40000', 'KlarstellungsSatzung'), ('40001', 'EntwicklungsSatzung'), ('40002', 'ErgaenzungsSatzung'), ('5000', 'AussenbereichsSatzung'), ('7000', 'OertlicheBauvorschrift'), ('9999', 'Sonstiges')], db_index=True, default='1000', max_length=5, verbose_name='Typ des vorliegenden Bebauungsplans.')),
                ('gemeinde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplanung_light.administrativeorganization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
