# Generated by Django 4.2.21 on 2025-06-04 12:04

from django.db import migrations, models
import uuid
import xplanung_light.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0003_alter_administrativeorganization_vs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='bplan',
            name='xplan_gml',
            field=models.FileField(blank=True, null=True, upload_to=xplanung_light.models.XPlan.get_upload_path, verbose_name='XPlan GML-Dokument'),
        ),
        migrations.AddField(
            model_name='bplan',
            name='xplan_gml_version',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='XPlan GML-Dokument Version'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='xplan_gml',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='XPlan GML-Dokument'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='xplan_gml_version',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='XPlan GML-Dokument Version'),
        ),
    ]
