# Generated by Django 4.2.21 on 2025-06-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0004_bplan_generic_id_bplan_xplan_gml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='inkrafttretens_datum',
            field=models.DateField(blank=True, help_text='Datum des Inkrafttretens', null=True, verbose_name='Datum des Inkrafttretens'),
        ),
        migrations.AddField(
            model_name='bplan',
            name='staedtebaulicher_vetrag',
            field=models.BooleanField(blank=True, help_text='Gibt an, ob es zum Plan einen städtebaulichen Vertrag gibt.', null=True, verbose_name='Städtebaulicher Vertrag'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='inkrafttretens_datum',
            field=models.DateField(blank=True, help_text='Datum des Inkrafttretens', null=True, verbose_name='Datum des Inkrafttretens'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='staedtebaulicher_vetrag',
            field=models.BooleanField(blank=True, help_text='Gibt an, ob es zum Plan einen städtebaulichen Vertrag gibt.', null=True, verbose_name='Städtebaulicher Vertrag'),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='xplan_gml',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='XPlan GML-Dokument'),
        ),
    ]
