# Generated by Django 4.2.21 on 2025-06-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0005_bplan_inkrafttretens_datum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bplan',
            old_name='staedtebaulicher_vetrag',
            new_name='staedtebaulicher_vertrag',
        ),
        migrations.RenameField(
            model_name='historicalbplan',
            old_name='staedtebaulicher_vetrag',
            new_name='staedtebaulicher_vertrag',
        ),
    ]
