# Generated by Django 4.2.21 on 2025-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0006_rename_staedtebaulicher_vetrag_bplan_staedtebaulicher_vertrag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='aufstellungsbeschluss_datum',
            field=models.DateField(blank=True, help_text='Datum des Aufstellungsbeschlusses', null=True, verbose_name='Datum des Aufstellungsbeschlusses'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='aufstellungsbeschluss_datum',
            field=models.DateField(blank=True, help_text='Datum des Aufstellungsbeschlusses', null=True, verbose_name='Datum des Aufstellungsbeschlusses'),
        ),
    ]
