# Generated by Django 4.2.21 on 2025-06-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0007_bplan_aufstellungsbeschluss_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplan',
            name='staedtebaulicher_vertrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob es zum Plan einen städtebaulichen Vertrag gibt.', verbose_name='Städtebaulicher Vertrag'),
        ),
        migrations.AlterField(
            model_name='historicalbplan',
            name='staedtebaulicher_vertrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob es zum Plan einen städtebaulichen Vertrag gibt.', verbose_name='Städtebaulicher Vertrag'),
        ),
    ]
