# Generated by Django 4.2.21 on 2025-06-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0008_alter_bplan_staedtebaulicher_vertrag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='durchfuehrungs_vertrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob für das Planungsgebiet einen Durchführungsvertrag (Kombination aus Städtebaulichen Vertrag und Erschließungsvertrag) gibt.', verbose_name='Durchführungsvertrag'),
        ),
        migrations.AddField(
            model_name='bplan',
            name='erschliessungs_vertrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob es für den Plan einen Erschließungsvertrag gibt.', verbose_name='Erschließungsvertrag'),
        ),
        migrations.AddField(
            model_name='bplan',
            name='gruenordnungsplan',
            field=models.BooleanField(default=False, help_text='Gibt an, ob für den Plan ein zugehöriger Grünordnungsplan existiert.', verbose_name='Grünordnungsplan'),
        ),
        migrations.AddField(
            model_name='bplan',
            name='satzungsbeschluss_datum',
            field=models.DateField(blank=True, help_text='Datum des Satzungsbeschlusses', null=True, verbose_name='Datum des Satzungsbeschlusses'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='durchfuehrungs_vertrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob für das Planungsgebiet einen Durchführungsvertrag (Kombination aus Städtebaulichen Vertrag und Erschließungsvertrag) gibt.', verbose_name='Durchführungsvertrag'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='erschliessungs_vertrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob es für den Plan einen Erschließungsvertrag gibt.', verbose_name='Erschließungsvertrag'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='gruenordnungsplan',
            field=models.BooleanField(default=False, help_text='Gibt an, ob für den Plan ein zugehöriger Grünordnungsplan existiert.', verbose_name='Grünordnungsplan'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='satzungsbeschluss_datum',
            field=models.DateField(blank=True, help_text='Datum des Satzungsbeschlusses', null=True, verbose_name='Datum des Satzungsbeschlusses'),
        ),
    ]
