# Generated by Django 4.2.21 on 2025-06-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0009_bplan_durchfuehrungs_vertrag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='ausfertigungs_datum',
            field=models.DateField(blank=True, help_text='Datum der Ausfertigung', null=True, verbose_name='Datum der Ausfertigung'),
        ),
        migrations.AddField(
            model_name='bplan',
            name='rechtsverordnungs_datum',
            field=models.DateField(blank=True, help_text='Datum der Rechtsverordnung', null=True, verbose_name='Datum der Rechtsverordnung'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='ausfertigungs_datum',
            field=models.DateField(blank=True, help_text='Datum der Ausfertigung', null=True, verbose_name='Datum der Ausfertigung'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='rechtsverordnungs_datum',
            field=models.DateField(blank=True, help_text='Datum der Rechtsverordnung', null=True, verbose_name='Datum der Rechtsverordnung'),
        ),
    ]
