# Generated by Django 4.2.21 on 2025-06-06 06:15

from django.db import migrations, models
import django.db.models.deletion
import uuid
import xplanung_light.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0010_bplan_ausfertigungs_datum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPlanSpezExterneReferenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(default='Unbekannt', help_text='Name bzw. Titel des referierten Dokuments. Der Standardname ist "Unbekannt".', max_length=2048, verbose_name='Name des Dokumentes')),
                ('typ', models.CharField(choices=[('1000', 'Beschreibung'), ('1010', 'Begruendung'), ('1020', 'Legende')], db_index=True, default='1000', help_text='Typ / Inhalt des referierten Dokuments oder Rasterplans', max_length=5, verbose_name='Typ / Inhalt des referierten Dokuments oder Rasterplans')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=xplanung_light.models.BPlanSpezExterneReferenz.get_upload_path, verbose_name='Dokument')),
                ('bplan', models.ForeignKey(help_text='BPlan', on_delete=django.db.models.deletion.CASCADE, to='xplanung_light.bplan', verbose_name='BPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
