# Generated by Django 4.2.21 on 2025-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0012_alter_bplanspezexternereferenz_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanspezexternereferenz',
            name='aus_archiv',
            field=models.BooleanField(default=False, help_text='Gibt an, ob der Anhang ursprünglich aus einem hochgeladenem ZIP-Archiv stammt.', verbose_name='Anhang stammt aus hochgeladenem ZIP-Archiv'),
        ),
    ]
