# Generated by Django 4.2.21 on 2025-06-27 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0013_bplanspezexternereferenz_aus_archiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplanspezexternereferenz',
            name='bplan',
            field=simple_history.models.HistoricForeignKey(help_text='BPlan', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='xplanung_light.bplan', verbose_name='BPlan'),
        ),
        migrations.CreateModel(
            name='HistoricalBPlanSpezExterneReferenz',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(default='Unbekannt', help_text='Name bzw. Titel des referierten Dokuments. Der Standardname ist "Unbekannt".', max_length=2048, verbose_name='Name des Dokumentes')),
                ('typ', models.CharField(choices=[('1000', 'Beschreibung'), ('1010', 'Begruendung'), ('1020', 'Legende'), ('1030', 'Rechtsplan'), ('1040', 'Plangrundlage'), ('1050', 'Umweltbericht'), ('1060', 'Satzung'), ('1065', 'Verordnung'), ('1070', 'Karte'), ('1080', 'Erlaeuterung'), ('1090', 'ZusammenfassendeErklaerung'), ('2000', 'Koordinatenliste'), ('2100', 'Grundstuecksverzeichnis'), ('2200', 'Pflanzliste'), ('2300', 'Gruenordnungsplan'), ('2400', 'Erschliessungsvertrag'), ('2500', 'Durchfuehrungsvertrag'), ('2600', 'StaedtebaulicherVertrag'), ('2700', 'UmweltbezogeneStellungnahmen'), ('2800', 'Beschluss'), ('2900', 'VorhabenUndErschliessungsplan'), ('3000', 'MetadatenPlan'), ('3100', 'StaedtebaulEntwicklungskonzeptInnenentwicklung'), ('4000', 'Genehmigung'), ('5000', 'Bekanntmachung'), ('6000', 'Schutzgebietsverordnung'), ('9998', 'Rechtsverbindlich'), ('9999', 'Informell')], db_index=True, default='1000', help_text='Typ / Inhalt des referierten Dokuments oder Rasterplans', max_length=5, verbose_name='Typ / Inhalt des referierten Dokuments oder Rasterplans')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dokument')),
                ('aus_archiv', models.BooleanField(default=False, help_text='Gibt an, ob der Anhang ursprünglich aus einem hochgeladenem ZIP-Archiv stammt.', verbose_name='Anhang stammt aus hochgeladenem ZIP-Archiv')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bplan', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='BPlan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.bplan', verbose_name='BPlan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical b plan spez externe referenz',
                'verbose_name_plural': 'historical b plan spez externe referenzs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
