# Generated by Django 4.2.21 on 2025-06-30 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0014_alter_bplanspezexternereferenz_bplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBPlanBeteiligung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('bekanntmachung_datum', models.DateField(help_text='Datum der Bekanntmachung', verbose_name='Datum der Bekanntmachung')),
                ('start_datum', models.DateField(help_text='Beginn der Beteiligung', verbose_name='Beginn der Beteiligung')),
                ('end_datum', models.DateField(help_text='Ende der Beteiligung', verbose_name='Ende der Beteiligung')),
                ('typ', models.CharField(choices=[('1000', 'Auslegung'), ('2000', 'Träger öffentlicher Belange')], db_index=True, default='1000', help_text='Typ des Beteiligungsverfahrens - aktuell Auslegung oder TÖB', max_length=5, verbose_name='Typ des Beteiligungsverfahrens')),
                ('publikation_internet', models.URLField(blank=True, help_text='Link zur Publikation auf der Hompage der jeweiligen Organisation', null=True, verbose_name='Publikation im Internet')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bplan', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='BPlan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.bplan', verbose_name='BPlan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical b plan beteiligung',
                'verbose_name_plural': 'historical b plan beteiligungs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BPlanBeteiligung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('bekanntmachung_datum', models.DateField(help_text='Datum der Bekanntmachung', verbose_name='Datum der Bekanntmachung')),
                ('start_datum', models.DateField(help_text='Beginn der Beteiligung', verbose_name='Beginn der Beteiligung')),
                ('end_datum', models.DateField(help_text='Ende der Beteiligung', verbose_name='Ende der Beteiligung')),
                ('typ', models.CharField(choices=[('1000', 'Auslegung'), ('2000', 'Träger öffentlicher Belange')], db_index=True, default='1000', help_text='Typ des Beteiligungsverfahrens - aktuell Auslegung oder TÖB', max_length=5, verbose_name='Typ des Beteiligungsverfahrens')),
                ('publikation_internet', models.URLField(blank=True, help_text='Link zur Publikation auf der Hompage der jeweiligen Organisation', null=True, verbose_name='Publikation im Internet')),
                ('bplan', simple_history.models.HistoricForeignKey(help_text='BPlan', on_delete=django.db.models.deletion.CASCADE, related_name='beteiligungen', to='xplanung_light.bplan', verbose_name='BPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
