# Generated by Django 4.2.21 on 2025-06-30 14:13

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0016_remove_historicalbplan_gemeinde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBPlan_gemeinde',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('administrativeorganization', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.administrativeorganization')),
                ('bplan', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.bplan')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicalbplan')),
            ],
            options={
                'verbose_name': 'HistoricalBPlan_gemeinde',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
