# Generated by Django 4.2.21 on 2025-07-04 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0017_historicalbplan_gemeinde'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(help_text='Offizieller Name der Organisation - z.B. Bauamt Pirmasens', max_length=1024, verbose_name='Name der Kontaktorganisation')),
                ('unit', models.CharField(blank=True, help_text='Name der zuständigen Einheit innerhalb der Organisation - z.B. Auskunftsstelle Bauleitplanung', max_length=1024, null=True, verbose_name='Name der Einheit/Referat')),
                ('person', models.CharField(blank=True, help_text='Name einer Person die direkt kontaktiert werden kann, wenn man Informationen zu den Bauleitplänen benötigt.', max_length=1024, null=True, verbose_name='Name einer Kontaktperson')),
                ('phone', models.CharField(max_length=256, verbose_name='Telefon')),
                ('facsimile', models.CharField(blank=True, max_length=256, null=True, verbose_name='Fax')),
                ('email', models.EmailField(max_length=512, verbose_name='EMail')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='Homepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('identifier', models.CharField(help_text='Offizieller Identifikatir / Name der Lizenz', max_length=1024, verbose_name='Identifikator / Name')),
                ('label', models.CharField(help_text='Offizieller Titel / Bezeichnung der Lizenz un deutscher Sprache', max_length=1024, verbose_name='Titel / Bezeichnung der Lizenz')),
                ('url', models.URLField(help_text='Verweis auf eine Seite mit einer genauen Beschreibung der Lizenz', verbose_name='URL')),
                ('is_open', models.BooleanField(default=False, verbose_name='Lizenz ist OpenData kompatibel')),
                ('need_source', models.BooleanField(default=False, verbose_name='Lizenz ist erfordert Quellenangabe')),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Symbol für die Anzeige')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='published_data_accessrights',
            field=models.CharField(blank=True, help_text='Angaben zu vorhandenen Zugriffsbeschränkungen (Ist der Zugriff für jedermann möglich, oder nur für besonders berechtigte Personengruppen)', max_length=4096, null=True, verbose_name='Zugriffsbeschränkungen'),
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='published_data_license_source_note',
            field=models.CharField(blank=True, help_text='Art der Quellenangabe - falls Lizenz diese erfodert', max_length=4096, null=True, verbose_name='Quellenangabe'),
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='published_data_rights',
            field=models.CharField(blank=True, help_text='Sonstige rechtliche Hinweise, die nicht von den Angaben zu Lizenzen oder Zugriffsbeschränkungen abgedeckt sind', max_length=4096, null=True, verbose_name='Sonstige rechtliche Hinweise'),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='published_data_accessrights',
            field=models.CharField(blank=True, help_text='Angaben zu vorhandenen Zugriffsbeschränkungen (Ist der Zugriff für jedermann möglich, oder nur für besonders berechtigte Personengruppen)', max_length=4096, null=True, verbose_name='Zugriffsbeschränkungen'),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='published_data_license_source_note',
            field=models.CharField(blank=True, help_text='Art der Quellenangabe - falls Lizenz diese erfodert', max_length=4096, null=True, verbose_name='Quellenangabe'),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='published_data_rights',
            field=models.CharField(blank=True, help_text='Sonstige rechtliche Hinweise, die nicht von den Angaben zu Lizenzen oder Zugriffsbeschränkungen abgedeckt sind', max_length=4096, null=True, verbose_name='Sonstige rechtliche Hinweise'),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='gemeinde',
            field=models.ManyToManyField(to='xplanung_light.administrativeorganization', verbose_name='Gemeinde(n)'),
        ),
        migrations.CreateModel(
            name='HistoricalLicense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('identifier', models.CharField(help_text='Offizieller Identifikatir / Name der Lizenz', max_length=1024, verbose_name='Identifikator / Name')),
                ('label', models.CharField(help_text='Offizieller Titel / Bezeichnung der Lizenz un deutscher Sprache', max_length=1024, verbose_name='Titel / Bezeichnung der Lizenz')),
                ('url', models.URLField(help_text='Verweis auf eine Seite mit einer genauen Beschreibung der Lizenz', verbose_name='URL')),
                ('is_open', models.BooleanField(default=False, verbose_name='Lizenz ist OpenData kompatibel')),
                ('need_source', models.BooleanField(default=False, verbose_name='Lizenz ist erfordert Quellenangabe')),
                ('symbol', models.TextField(blank=True, max_length=100, null=True, verbose_name='Symbol für die Anzeige')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical license',
                'verbose_name_plural': 'historical licenses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContactOrganization',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(help_text='Offizieller Name der Organisation - z.B. Bauamt Pirmasens', max_length=1024, verbose_name='Name der Kontaktorganisation')),
                ('unit', models.CharField(blank=True, help_text='Name der zuständigen Einheit innerhalb der Organisation - z.B. Auskunftsstelle Bauleitplanung', max_length=1024, null=True, verbose_name='Name der Einheit/Referat')),
                ('person', models.CharField(blank=True, help_text='Name einer Person die direkt kontaktiert werden kann, wenn man Informationen zu den Bauleitplänen benötigt.', max_length=1024, null=True, verbose_name='Name einer Kontaktperson')),
                ('phone', models.CharField(max_length=256, verbose_name='Telefon')),
                ('facsimile', models.CharField(blank=True, max_length=256, null=True, verbose_name='Fax')),
                ('email', models.EmailField(max_length=512, verbose_name='EMail')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='Homepage')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contact organization',
                'verbose_name_plural': 'historical contact organizations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='published_data_contact_point',
            field=simple_history.models.HistoricForeignKey(blank=True, help_text='Auswahl einer Kontaktstelle für die publizierten Pläne der Organisation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplanung_light.contactorganization', verbose_name='Kontaktstelle für die publizierten Pläne der Organisation'),
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='published_data_license',
            field=simple_history.models.HistoricForeignKey(blank=True, help_text='Auswahl einer standardisierten Lizenz', null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplanung_light.license', verbose_name='Standardisierte Lizenz'),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='published_data_contact_point',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='Auswahl einer Kontaktstelle für die publizierten Pläne der Organisation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.contactorganization', verbose_name='Kontaktstelle für die publizierten Pläne der Organisation'),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='published_data_license',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='Auswahl einer standardisierten Lizenz', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.license', verbose_name='Standardisierte Lizenz'),
        ),
    ]
