# Generated by Django 4.2.21 on 2025-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0019_alter_administrativeorganization_published_data_accessrights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeorganization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
