# Generated by Django 4.2.21 on 2025-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0021_adminorgauser_adminorgaowner_adminorgainvitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminorgauser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='adminorgauser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Nutzer ist Administrator für Organisation'),
        ),
    ]
