# Generated by Django 4.2.21 on 2025-07-15 08:53

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0023_administrativeorganization_coat_of_arms_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativeorganization',
            name='published_data_contact_point',
        ),
        migrations.RemoveField(
            model_name='historicaladministrativeorganization',
            name='published_data_contact_point',
        ),
        migrations.AddField(
            model_name='contactorganization',
            name='gemeinde',
            field=models.ManyToManyField(to='xplanung_light.administrativeorganization', verbose_name='Kontakt für Gemeinde(n)'),
        ),
        migrations.CreateModel(
            name='HistoricalContactOrganization_gemeinde',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('administrativeorganization', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.administrativeorganization')),
                ('contactorganization', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.contactorganization')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicalcontactorganization')),
            ],
            options={
                'verbose_name': 'HistoricalContactOrganization_gemeinde',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
