# Generated by Django 4.2.21 on 2025-08-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0024_remove_administrativeorganization_published_data_contact_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='beschreibung',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Kommentierende Beschreibung des Plans. Es wird empfohlen, eine Planbeschreibung zu erfassen.'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='beschreibung',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Kommentierende Beschreibung des Plans. Es wird empfohlen, eine Planbeschreibung zu erfassen.'),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='nummer',
            field=models.CharField(max_length=56, verbose_name='Nummer des Plans.'),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='rechtsverordnungs_datum',
            field=models.DateField(blank=True, help_text='Datum der Rechtsverordnung, falls ein Bebauungsplan als Rechtsverordnung beschlossen wird.', null=True, verbose_name='Datum der Rechtsverordnung'),
        ),
        migrations.AlterField(
            model_name='bplan',
            name='satzungsbeschluss_datum',
            field=models.DateField(blank=True, help_text='Datum des Satzungsbeschlusses, falls ein Bebauungsplan als Satzung beschlossen wird.', null=True, verbose_name='Datum des Satzungsbeschlusses'),
        ),
        migrations.AlterField(
            model_name='contactorganization',
            name='gemeinde',
            field=models.ManyToManyField(related_name='contacts', to='xplanung_light.administrativeorganization', verbose_name='Kontakt für Gemeinde(n)'),
        ),
        migrations.AlterField(
            model_name='contactorganization',
            name='name',
            field=models.CharField(help_text='Offizieller Name der Kontaktstelle - z.B. Bauamt Pirmasens', max_length=1024, verbose_name='Name der Kontaktstelle'),
        ),
        migrations.AlterField(
            model_name='contactorganization',
            name='unit',
            field=models.CharField(blank=True, help_text='Name der zuständigen Einheit innerhalb der Kontaktstelle - z.B. Auskunftsstelle Bauleitplanung', max_length=1024, null=True, verbose_name='Name der Einheit/Referat'),
        ),
        migrations.AlterField(
            model_name='historicalbplan',
            name='nummer',
            field=models.CharField(max_length=56, verbose_name='Nummer des Plans.'),
        ),
        migrations.AlterField(
            model_name='historicalbplan',
            name='rechtsverordnungs_datum',
            field=models.DateField(blank=True, help_text='Datum der Rechtsverordnung, falls ein Bebauungsplan als Rechtsverordnung beschlossen wird.', null=True, verbose_name='Datum der Rechtsverordnung'),
        ),
        migrations.AlterField(
            model_name='historicalbplan',
            name='satzungsbeschluss_datum',
            field=models.DateField(blank=True, help_text='Datum des Satzungsbeschlusses, falls ein Bebauungsplan als Satzung beschlossen wird.', null=True, verbose_name='Datum des Satzungsbeschlusses'),
        ),
        migrations.AlterField(
            model_name='historicalcontactorganization',
            name='name',
            field=models.CharField(help_text='Offizieller Name der Kontaktstelle - z.B. Bauamt Pirmasens', max_length=1024, verbose_name='Name der Kontaktstelle'),
        ),
        migrations.AlterField(
            model_name='historicalcontactorganization',
            name='unit',
            field=models.CharField(blank=True, help_text='Name der zuständigen Einheit innerhalb der Kontaktstelle - z.B. Auskunftsstelle Bauleitplanung', max_length=1024, null=True, verbose_name='Name der Einheit/Referat'),
        ),
    ]
