# Generated by Django 4.2.21 on 2025-08-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0025_bplan_beschreibung_historicalbplan_beschreibung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeorganization',
            name='name_part',
            field=models.CharField(blank=True, help_text='Offizieller eines Teils der Gebietskörperschaft - z.B. Arzheim - als Ortsbezirk 2 der Stadt Koblenz', max_length=1024, null=True, verbose_name='Name des Teils der Gebietskörperschaft'),
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='ts',
            field=models.CharField(blank=True, help_text='Eindeutiger, maximal vierstelliger Schlüssel einen Teil einer Gebietskörperschaft - von Bundesland zu Bundesland unterschiedlich geregelt!', max_length=4, null=True, verbose_name='Ortsteilschlüssel'),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='name_part',
            field=models.CharField(blank=True, help_text='Offizieller eines Teils der Gebietskörperschaft - z.B. Arzheim - als Ortsbezirk 2 der Stadt Koblenz', max_length=1024, null=True, verbose_name='Name des Teils der Gebietskörperschaft'),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='ts',
            field=models.CharField(blank=True, help_text='Eindeutiger, maximal vierstelliger Schlüssel einen Teil einer Gebietskörperschaft - von Bundesland zu Bundesland unterschiedlich geregelt!', max_length=4, null=True, verbose_name='Ortsteilschlüssel'),
        ),
    ]
