# Generated by Django 4.2.21 on 2025-08-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0026_administrativeorganization_name_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='untergangs_datum',
            field=models.DateField(blank=True, help_text='Datum, an dem der Plan (z.B. durch Ratsbeschluss oder Gerichtsurteil) aufgehoben oder für nichtig erklärt wurde.', null=True, verbose_name='Untergangsdatum des Plans'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='untergangs_datum',
            field=models.DateField(blank=True, help_text='Datum, an dem der Plan (z.B. durch Ratsbeschluss oder Gerichtsurteil) aufgehoben oder für nichtig erklärt wurde.', null=True, verbose_name='Untergangsdatum des Plans'),
        ),
        migrations.AlterField(
            model_name='administrativeorganization',
            name='name_part',
            field=models.CharField(blank=True, help_text='Offizieller Namen eines Teils der Gebietskörperschaft - z.B. Arzheim - als Ortsbezirk 2 der Stadt Koblenz', max_length=1024, null=True, verbose_name='Name des Teils der Gebietskörperschaft'),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeorganization',
            name='name_part',
            field=models.CharField(blank=True, help_text='Offizieller Namen eines Teils der Gebietskörperschaft - z.B. Arzheim - als Ortsbezirk 2 der Stadt Koblenz', max_length=1024, null=True, verbose_name='Name des Teils der Gebietskörperschaft'),
        ),
    ]
