# Generated by Django 4.2.21 on 2025-09-08 10:37

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0028_alter_bplan_untergangs_datum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(help_text='Offizieller Name des raumbezogenen Plans', max_length=2048, verbose_name='Name des Plans')),
                ('nummer', models.CharField(max_length=56, verbose_name='Nummer des Plans.')),
                ('beschreibung', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Kommentierende Beschreibung des Plans. Es wird empfohlen, eine Planbeschreibung zu erfassen.')),
                ('untergangs_datum', models.DateField(blank=True, help_text='Datum, an dem der Plan (z.B. durch Ratsbeschluss oder Gerichtsurteil) aufgehoben oder für nichtig erklärt wurde.', null=True, verbose_name='Datum des Untergangs')),
                ('geltungsbereich', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Grenze des räumlichen Geltungsbereiches des Plans.')),
                ('xplan_gml', models.FileField(blank=True, null=True, upload_to='', verbose_name='XPlan GML-Dokument')),
                ('xplan_gml_version', models.CharField(blank=True, max_length=5, null=True, verbose_name='XPlan GML-Dokument Version')),
                ('planart', models.CharField(choices=[('1000', 'FPlan'), ('2000', 'GemeinsamerFPlan'), ('3000', 'RegFPlan'), ('4000', 'FPlanRegPlan'), ('5000', 'SachlicherTeilplan'), ('6000', 'Sonstiges')], db_index=True, default='1000', max_length=5, verbose_name='Typ des vorliegenden Flächennutzungsplans.')),
                ('aufstellungsbeschluss_datum', models.DateField(blank=True, help_text='Datum des Aufstellungsbeschlusses', null=True, verbose_name='Datum des Aufstellungsbeschlusses')),
                ('gemeinde', models.ManyToManyField(to='xplanung_light.administrativeorganization', verbose_name='Gemeinde(n)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(help_text='Offizieller Name des raumbezogenen Plans', max_length=2048, verbose_name='Name des Plans')),
                ('nummer', models.CharField(max_length=56, verbose_name='Nummer des Plans.')),
                ('beschreibung', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Kommentierende Beschreibung des Plans. Es wird empfohlen, eine Planbeschreibung zu erfassen.')),
                ('untergangs_datum', models.DateField(blank=True, help_text='Datum, an dem der Plan (z.B. durch Ratsbeschluss oder Gerichtsurteil) aufgehoben oder für nichtig erklärt wurde.', null=True, verbose_name='Datum des Untergangs')),
                ('geltungsbereich', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Grenze des räumlichen Geltungsbereiches des Plans.')),
                ('xplan_gml', models.TextField(blank=True, max_length=100, null=True, verbose_name='XPlan GML-Dokument')),
                ('xplan_gml_version', models.CharField(blank=True, max_length=5, null=True, verbose_name='XPlan GML-Dokument Version')),
                ('planart', models.CharField(choices=[('1000', 'FPlan'), ('2000', 'GemeinsamerFPlan'), ('3000', 'RegFPlan'), ('4000', 'FPlanRegPlan'), ('5000', 'SachlicherTeilplan'), ('6000', 'Sonstiges')], db_index=True, default='1000', max_length=5, verbose_name='Typ des vorliegenden Flächennutzungsplans.')),
                ('aufstellungsbeschluss_datum', models.DateField(blank=True, help_text='Datum des Aufstellungsbeschlusses', null=True, verbose_name='Datum des Aufstellungsbeschlusses')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical f plan',
                'verbose_name_plural': 'historical f plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligung',
            name='typ',
            field=models.CharField(choices=[('20001', 'Frühzeitige Trägerbeteiligung'), ('10001', 'Frühzeitige Öffentlichkeitsbeteiligung'), ('2000', 'Träger öffentlicher Belange'), ('1000', 'Öffentliche Auslegung')], db_index=True, default='1000', help_text='Typ des Beteiligungsverfahrens - aktuell Auslegung oder TÖB', max_length=5, verbose_name='Typ des Beteiligungsverfahrens'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligung',
            name='typ',
            field=models.CharField(choices=[('20001', 'Frühzeitige Trägerbeteiligung'), ('10001', 'Frühzeitige Öffentlichkeitsbeteiligung'), ('2000', 'Träger öffentlicher Belange'), ('1000', 'Öffentliche Auslegung')], db_index=True, default='1000', help_text='Typ des Beteiligungsverfahrens - aktuell Auslegung oder TÖB', max_length=5, verbose_name='Typ des Beteiligungsverfahrens'),
        ),
        migrations.CreateModel(
            name='HistoricalFPlanSpezExterneReferenz',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(default='Unbekannt', help_text='Name bzw. Titel des referierten Dokuments. Der Standardname ist "Unbekannt".', max_length=2048, verbose_name='Name des Dokumentes')),
                ('typ', models.CharField(choices=[('1000', 'Beschreibung'), ('1010', 'Begruendung'), ('1020', 'Legende'), ('1030', 'Rechtsplan'), ('1040', 'Plangrundlage'), ('1050', 'Umweltbericht'), ('1060', 'Satzung'), ('1065', 'Verordnung'), ('1070', 'Karte'), ('1080', 'Erlaeuterung'), ('1090', 'ZusammenfassendeErklaerung'), ('2000', 'Koordinatenliste'), ('2100', 'Grundstuecksverzeichnis'), ('2200', 'Pflanzliste'), ('2300', 'Gruenordnungsplan'), ('2400', 'Erschliessungsvertrag'), ('2500', 'Durchfuehrungsvertrag'), ('2600', 'StaedtebaulicherVertrag'), ('2700', 'UmweltbezogeneStellungnahmen'), ('2800', 'Beschluss'), ('2900', 'VorhabenUndErschliessungsplan'), ('3000', 'MetadatenPlan'), ('3100', 'StaedtebaulEntwicklungskonzeptInnenentwicklung'), ('4000', 'Genehmigung'), ('5000', 'Bekanntmachung'), ('6000', 'Schutzgebietsverordnung'), ('9998', 'Rechtsverbindlich'), ('9999', 'Informell'), ('99999', 'GeoreferenzierterScan')], db_index=True, default='1000', help_text='Typ / Inhalt des referierten Dokuments oder Rasterplans', max_length=5, verbose_name='Typ / Inhalt des referierten Dokuments oder Rasterplans')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dokument')),
                ('aus_archiv', models.BooleanField(default=False, help_text='Gibt an, ob der Anhang ursprünglich aus einem hochgeladenem ZIP-Archiv stammt.', verbose_name='Anhang stammt aus hochgeladenem ZIP-Archiv')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fplan', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='FPlan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplan', verbose_name='FPlan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical f plan spez externe referenz',
                'verbose_name_plural': 'historical f plan spez externe referenzs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFPlanBeteiligung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('bekanntmachung_datum', models.DateField(help_text='Datum der Bekanntmachung des Verfahrens', verbose_name='Datum der Bekanntmachung')),
                ('start_datum', models.DateField(help_text='Datum des Beginns des Beteiligungsverfahrens', verbose_name='Beginn')),
                ('end_datum', models.DateField(help_text='Enddatum des Beteiligungsverfahrens', verbose_name='Ende')),
                ('typ', models.CharField(choices=[('20001', 'Frühzeitige Trägerbeteiligung'), ('10001', 'Frühzeitige Öffentlichkeitsbeteiligung'), ('2000', 'Träger öffentlicher Belange'), ('1000', 'Öffentliche Auslegung')], db_index=True, default='1000', help_text='Typ des Beteiligungsverfahrens - aktuell Auslegung oder TÖB', max_length=5, verbose_name='Typ des Beteiligungsverfahrens')),
                ('publikation_internet', models.URLField(blank=True, help_text='Link zur Publikation auf der Hompage der jeweiligen Organisation', null=True, verbose_name='Publikation im Internet')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fplan', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='FPlan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplan', verbose_name='FPlan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical f plan beteiligung',
                'verbose_name_plural': 'historical f plan beteiligungs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFPlan_gemeinde',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('administrativeorganization', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.administrativeorganization')),
                ('fplan', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplan')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicalfplan')),
            ],
            options={
                'verbose_name': 'HistoricalFPlan_gemeinde',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FPlanSpezExterneReferenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(default='Unbekannt', help_text='Name bzw. Titel des referierten Dokuments. Der Standardname ist "Unbekannt".', max_length=2048, verbose_name='Name des Dokumentes')),
                ('typ', models.CharField(choices=[('1000', 'Beschreibung'), ('1010', 'Begruendung'), ('1020', 'Legende'), ('1030', 'Rechtsplan'), ('1040', 'Plangrundlage'), ('1050', 'Umweltbericht'), ('1060', 'Satzung'), ('1065', 'Verordnung'), ('1070', 'Karte'), ('1080', 'Erlaeuterung'), ('1090', 'ZusammenfassendeErklaerung'), ('2000', 'Koordinatenliste'), ('2100', 'Grundstuecksverzeichnis'), ('2200', 'Pflanzliste'), ('2300', 'Gruenordnungsplan'), ('2400', 'Erschliessungsvertrag'), ('2500', 'Durchfuehrungsvertrag'), ('2600', 'StaedtebaulicherVertrag'), ('2700', 'UmweltbezogeneStellungnahmen'), ('2800', 'Beschluss'), ('2900', 'VorhabenUndErschliessungsplan'), ('3000', 'MetadatenPlan'), ('3100', 'StaedtebaulEntwicklungskonzeptInnenentwicklung'), ('4000', 'Genehmigung'), ('5000', 'Bekanntmachung'), ('6000', 'Schutzgebietsverordnung'), ('9998', 'Rechtsverbindlich'), ('9999', 'Informell'), ('99999', 'GeoreferenzierterScan')], db_index=True, default='1000', help_text='Typ / Inhalt des referierten Dokuments oder Rasterplans', max_length=5, verbose_name='Typ / Inhalt des referierten Dokuments oder Rasterplans')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Dokument')),
                ('aus_archiv', models.BooleanField(default=False, help_text='Gibt an, ob der Anhang ursprünglich aus einem hochgeladenem ZIP-Archiv stammt.', verbose_name='Anhang stammt aus hochgeladenem ZIP-Archiv')),
                ('fplan', simple_history.models.HistoricForeignKey(help_text='FPlan', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='xplanung_light.fplan', verbose_name='FPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FPlanBeteiligung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('bekanntmachung_datum', models.DateField(help_text='Datum der Bekanntmachung des Verfahrens', verbose_name='Datum der Bekanntmachung')),
                ('start_datum', models.DateField(help_text='Datum des Beginns des Beteiligungsverfahrens', verbose_name='Beginn')),
                ('end_datum', models.DateField(help_text='Enddatum des Beteiligungsverfahrens', verbose_name='Ende')),
                ('typ', models.CharField(choices=[('20001', 'Frühzeitige Trägerbeteiligung'), ('10001', 'Frühzeitige Öffentlichkeitsbeteiligung'), ('2000', 'Träger öffentlicher Belange'), ('1000', 'Öffentliche Auslegung')], db_index=True, default='1000', help_text='Typ des Beteiligungsverfahrens - aktuell Auslegung oder TÖB', max_length=5, verbose_name='Typ des Beteiligungsverfahrens')),
                ('publikation_internet', models.URLField(blank=True, help_text='Link zur Publikation auf der Hompage der jeweiligen Organisation', null=True, verbose_name='Publikation im Internet')),
                ('fplan', simple_history.models.HistoricForeignKey(help_text='FPlan', on_delete=django.db.models.deletion.CASCADE, related_name='beteiligungen', to='xplanung_light.fplan', verbose_name='FPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
