# Generated by Django 4.2.21 on 2025-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0029_fplan_historicalfplan_alter_bplanbeteiligung_typ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='public',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Informationen zum Plan über die frei verfügbaren Schnittstellen publiziert werden.', verbose_name='Plan öffentlich verfügbar'),
        ),
        migrations.AddField(
            model_name='fplan',
            name='planbeschluss_datum',
            field=models.DateField(blank=True, help_text='Datum des Planbeschlusses', null=True, verbose_name='Datum des Planbeschlusses'),
        ),
        migrations.AddField(
            model_name='fplan',
            name='public',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Informationen zum Plan über die frei verfügbaren Schnittstellen publiziert werden.', verbose_name='Plan öffentlich verfügbar'),
        ),
        migrations.AddField(
            model_name='fplan',
            name='wirksamkeits_datum',
            field=models.DateField(blank=True, help_text='Datum der Wirksamkeit', null=True, verbose_name='Datum der Wirksamkeit'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='public',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Informationen zum Plan über die frei verfügbaren Schnittstellen publiziert werden.', verbose_name='Plan öffentlich verfügbar'),
        ),
        migrations.AddField(
            model_name='historicalfplan',
            name='planbeschluss_datum',
            field=models.DateField(blank=True, help_text='Datum des Planbeschlusses', null=True, verbose_name='Datum des Planbeschlusses'),
        ),
        migrations.AddField(
            model_name='historicalfplan',
            name='public',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Informationen zum Plan über die frei verfügbaren Schnittstellen publiziert werden.', verbose_name='Plan öffentlich verfügbar'),
        ),
        migrations.AddField(
            model_name='historicalfplan',
            name='wirksamkeits_datum',
            field=models.DateField(blank=True, help_text='Datum der Wirksamkeit', null=True, verbose_name='Datum der Wirksamkeit'),
        ),
    ]
