# Generated by Django 4.2.21 on 2025-09-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0030_bplan_public_fplan_planbeschluss_datum_fplan_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='massstab',
            field=models.IntegerField(blank=True, default=1000, help_text='Der bei der Erstellung des Plans benutzte Kartenmaßstab.', null=True, verbose_name='Kartenmaßstab des Plans'),
        ),
        migrations.AddField(
            model_name='fplan',
            name='massstab',
            field=models.IntegerField(blank=True, default=1000, help_text='Der bei der Erstellung des Plans benutzte Kartenmaßstab.', null=True, verbose_name='Kartenmaßstab des Plans'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='massstab',
            field=models.IntegerField(blank=True, default=1000, help_text='Der bei der Erstellung des Plans benutzte Kartenmaßstab.', null=True, verbose_name='Kartenmaßstab des Plans'),
        ),
        migrations.AddField(
            model_name='historicalfplan',
            name='massstab',
            field=models.IntegerField(blank=True, default=1000, help_text='Der bei der Erstellung des Plans benutzte Kartenmaßstab.', null=True, verbose_name='Kartenmaßstab des Plans'),
        ),
    ]
