# Generated by Django 4.2.21 on 2025-09-17 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0031_bplan_massstab_fplan_massstab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplan',
            name='massstab',
            field=models.IntegerField(blank=True, default=1000, help_text='Der bei der Erstellung des Plans benutzter Kartenmaßstab.', null=True, verbose_name='Kartenmaßstab des Plans'),
        ),
        migrations.AlterField(
            model_name='fplan',
            name='massstab',
            field=models.IntegerField(blank=True, default=1000, help_text='Der bei der Erstellung des Plans benutzter Kartenmaßstab.', null=True, verbose_name='Kartenmaßstab des Plans'),
        ),
        migrations.AlterField(
            model_name='historicalbplan',
            name='massstab',
            field=models.IntegerField(blank=True, default=1000, help_text='Der bei der Erstellung des Plans benutzter Kartenmaßstab.', null=True, verbose_name='Kartenmaßstab des Plans'),
        ),
        migrations.AlterField(
            model_name='historicalfplan',
            name='massstab',
            field=models.IntegerField(blank=True, default=1000, help_text='Der bei der Erstellung des Plans benutzter Kartenmaßstab.', null=True, verbose_name='Kartenmaßstab des Plans'),
        ),
        migrations.CreateModel(
            name='HistoricalFPlanUvp',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('uvp_vp', models.BooleanField(default=False, help_text='Gibt an, ob bei der Aufstellung des Plan eine UVP Vorprüfung durchgeführt wurde.', verbose_name='UVP Vorprüfung durchgeführt')),
                ('uvp', models.BooleanField(default=False, help_text='Gibt an, ob bei der Aufstellung des Plan eine UVP durchgeführt wurde.', verbose_name='UVP durchgeführt')),
                ('typ', models.CharField(blank=True, choices=[('18.1: Feriendorf Außenbereich', (('18_1_1', '18.1.1 (X): Betten >= 300 oder GZ >= 200'), ('18_1_2', '18.1.2 (A): Betten >= 100 < 300 oder GZ >=80 < 200'))), ('18.2: Campingplatz Außenbereich', (('18_2_1', '18.2.1 (X): StPl 200+'), ('18_2_2', '18.2.2 (A): StPl >=50 < 200')))], db_index=True, help_text='Kategorie für Bauvorhaben gem. Anlage 1 UVPG - https://www.gesetze-im-internet.de/uvpg/anlage_1.html', max_length=7, null=True, verbose_name='Kategorie für Bauvorhaben gem. Anlage 1 UVPG')),
                ('uvp_beginn_datum', models.DateField(blank=True, help_text='Datum des Beginns der UVP.', null=True, verbose_name='Datum des Beginns der UVP')),
                ('uvp_ende_datum', models.DateField(blank=True, help_text='Datum des Abschlusses der UVP.', null=True, verbose_name='Datum des Abschlusses der UVP')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fplan', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='FPlan', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplan', verbose_name='FPlan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical f plan uvp',
                'verbose_name_plural': 'historical f plan uvps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FPlanUvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('uvp_vp', models.BooleanField(default=False, help_text='Gibt an, ob bei der Aufstellung des Plan eine UVP Vorprüfung durchgeführt wurde.', verbose_name='UVP Vorprüfung durchgeführt')),
                ('uvp', models.BooleanField(default=False, help_text='Gibt an, ob bei der Aufstellung des Plan eine UVP durchgeführt wurde.', verbose_name='UVP durchgeführt')),
                ('typ', models.CharField(blank=True, choices=[('18.1: Feriendorf Außenbereich', (('18_1_1', '18.1.1 (X): Betten >= 300 oder GZ >= 200'), ('18_1_2', '18.1.2 (A): Betten >= 100 < 300 oder GZ >=80 < 200'))), ('18.2: Campingplatz Außenbereich', (('18_2_1', '18.2.1 (X): StPl 200+'), ('18_2_2', '18.2.2 (A): StPl >=50 < 200')))], db_index=True, help_text='Kategorie für Bauvorhaben gem. Anlage 1 UVPG - https://www.gesetze-im-internet.de/uvpg/anlage_1.html', max_length=7, null=True, verbose_name='Kategorie für Bauvorhaben gem. Anlage 1 UVPG')),
                ('uvp_beginn_datum', models.DateField(blank=True, help_text='Datum des Beginns der UVP.', null=True, verbose_name='Datum des Beginns der UVP')),
                ('uvp_ende_datum', models.DateField(blank=True, help_text='Datum des Abschlusses der UVP.', null=True, verbose_name='Datum des Abschlusses der UVP')),
                ('fplan', simple_history.models.HistoricForeignKey(help_text='FPlan', on_delete=django.db.models.deletion.CASCADE, related_name='uvps', to='xplanung_light.fplan', verbose_name='FPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
