# Generated by Django 4.2.21 on 2025-09-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0032_alter_bplan_massstab_alter_fplan_massstab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fplanuvp',
            name='typ',
            field=models.CharField(blank=True, choices=[('1000', 'Strategische Umweltprüfung')], db_index=True, help_text='Kategorie für Umweltprüfungen - weitere Infos: https://www.umweltbundesamt.de/sites/default/files/medien/11850/publikationen/112_2023_texte_evaluation_der_praxis_der_strategischen_umweltpruefung_in_deutschland.pdf', max_length=7, null=True, verbose_name='Kategorie für Umweltprüfungen gem. UVPG'),
        ),
        migrations.AlterField(
            model_name='historicalfplanuvp',
            name='typ',
            field=models.CharField(blank=True, choices=[('1000', 'Strategische Umweltprüfung')], db_index=True, help_text='Kategorie für Umweltprüfungen - weitere Infos: https://www.umweltbundesamt.de/sites/default/files/medien/11850/publikationen/112_2023_texte_evaluation_der_praxis_der_strategischen_umweltpruefung_in_deutschland.pdf', max_length=7, null=True, verbose_name='Kategorie für Umweltprüfungen gem. UVPG'),
        ),
    ]
