# Generated by Django 4.2.21 on 2025-09-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0033_alter_fplanuvp_typ_alter_historicalfplanuvp_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fplanuvp',
            name='uvp_vp',
        ),
        migrations.RemoveField(
            model_name='historicalfplanuvp',
            name='uvp_vp',
        ),
    ]
