# Generated by Django 4.2.21 on 2025-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0035_bplanbeteiligungbeitrag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminorgauser',
            name='user_type',
            field=models.IntegerField(choices=[('1000', 'Beauskunftung von Plandaten'), ('2000', 'Verwalter von Plandaten'), ('3000', 'Abgabe von Stellungnahmen')], db_index=True, default='1000', verbose_name='Typ / Rolle des Nutzers'),
        ),
    ]
