# Generated by Django 4.2.21 on 2025-12-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0036_adminorgauser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligung',
            name='allow_online_beitrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Online-Verfahren für den Bteiligungsprozess zugelassen wird.', verbose_name='Online-Stellungnahme zulassen'),
        ),
        migrations.AddField(
            model_name='bplanbeteiligung',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Erläuternde Beschreibung des Beteiligungsverfahrens'),
        ),
        migrations.AddField(
            model_name='fplanbeteiligung',
            name='allow_online_beitrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Online-Verfahren für den Bteiligungsprozess zugelassen wird.', verbose_name='Online-Stellungnahme zulassen'),
        ),
        migrations.AddField(
            model_name='fplanbeteiligung',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Erläuternde Beschreibung des Beteiligungsverfahrens'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligung',
            name='allow_online_beitrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Online-Verfahren für den Bteiligungsprozess zugelassen wird.', verbose_name='Online-Stellungnahme zulassen'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligung',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Erläuternde Beschreibung des Beteiligungsverfahrens'),
        ),
        migrations.AddField(
            model_name='historicalfplanbeteiligung',
            name='allow_online_beitrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Online-Verfahren für den Bteiligungsprozess zugelassen wird.', verbose_name='Online-Stellungnahme zulassen'),
        ),
        migrations.AddField(
            model_name='historicalfplanbeteiligung',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Erläuternde Beschreibung des Beteiligungsverfahrens'),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligung',
            name='publikation_internet',
            field=models.URLField(blank=True, help_text='Link zur Publikation auf der Homepage der jeweiligen Organisation', null=True, verbose_name='Publikation im Internet'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligung',
            name='publikation_internet',
            field=models.URLField(blank=True, help_text='Link zur Publikation auf der Homepage der jeweiligen Organisation', null=True, verbose_name='Publikation im Internet'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligung',
            name='publikation_internet',
            field=models.URLField(blank=True, help_text='Link zur Publikation auf der Homepage der jeweiligen Organisation', null=True, verbose_name='Publikation im Internet'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligung',
            name='publikation_internet',
            field=models.URLField(blank=True, help_text='Link zur Publikation auf der Homepage der jeweiligen Organisation', null=True, verbose_name='Publikation im Internet'),
        ),
    ]
