# Generated by Django 4.2.21 on 2025-12-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0037_bplanbeteiligung_allow_online_beitrag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminorgauser',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='bplanbeteiligung',
            name='allow_online_beitrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Online-Verfahren für den Beteiligungsprozess zugelassen wird.', verbose_name='Online-Stellungnahme zulassen'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligung',
            name='allow_online_beitrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Online-Verfahren für den Beteiligungsprozess zugelassen wird.', verbose_name='Online-Stellungnahme zulassen'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligung',
            name='allow_online_beitrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Online-Verfahren für den Beteiligungsprozess zugelassen wird.', verbose_name='Online-Stellungnahme zulassen'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligung',
            name='allow_online_beitrag',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Online-Verfahren für den Beteiligungsprozess zugelassen wird.', verbose_name='Online-Stellungnahme zulassen'),
        ),
    ]
