# Generated by Django 4.2.21 on 2025-12-10 08:59

from django.db import migrations
import formset.richtext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0038_remove_adminorgauser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplanbeteiligung',
            name='beschreibung',
            field=formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Erläuternde Beschreibung des Beteiligungsverfahrens'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligung',
            name='beschreibung',
            field=formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Erläuternde Beschreibung des Beteiligungsverfahrens'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligung',
            name='beschreibung',
            field=formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Erläuternde Beschreibung des Beteiligungsverfahrens'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligung',
            name='beschreibung',
            field=formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Erläuternde Beschreibung des Beteiligungsverfahrens'),
        ),
    ]
