# Generated by Django 4.2.21 on 2025-12-10 09:56

from django.db import migrations
import formset.richtext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0039_alter_bplanbeteiligung_beschreibung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplanbeteiligungbeitrag',
            name='beschreibung',
            field=formset.richtext.fields.RichTextField(verbose_name='Beitrag / Kommentar (Textform)'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='beschreibung',
            field=formset.richtext.fields.RichTextField(verbose_name='Beitrag / Kommentar (Textform)'),
        ),
    ]
