# Generated by Django 4.2.21 on 2025-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0040_alter_bplanbeteiligungbeitrag_beschreibung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligungbeitrag',
            name='titel',
            field=models.CharField(default='dummy titel', help_text='Geben Sie hier bitte einen aussagekräftigen Titel für Ihren Beitrag an.', max_length=300, verbose_name='Titel des Beitrags'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='titel',
            field=models.CharField(default='dummy titel', help_text='Geben Sie hier bitte einen aussagekräftigen Titel für Ihren Beitrag an.', max_length=300, verbose_name='Titel des Beitrags'),
            preserve_default=False,
        ),
    ]
