# Generated by Django 4.2.21 on 2025-12-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0041_bplanbeteiligungbeitrag_titel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactorganization',
            name='datenschutz_link',
            field=models.URLField(default='http://example.com', help_text='Hier muss ein Link auf die Datenschutzerklärung der für die Verwaltung und Publikation zuständigen Kontaktstelle angegeben werden. Ohne Angabe dieses Links, sind Online-Stellungnahmen nicht möglich.', verbose_name='Link zur Datenschutzerklärung der Kontaktstelle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontactorganization',
            name='datenschutz_link',
            field=models.URLField(default='https://example.com', help_text='Hier muss ein Link auf die Datenschutzerklärung der für die Verwaltung und Publikation zuständigen Kontaktstelle angegeben werden. Ohne Angabe dieses Links, sind Online-Stellungnahmen nicht möglich.', verbose_name='Link zur Datenschutzerklärung der Kontaktstelle'),
            preserve_default=False,
        ),
    ]
