# Generated by Django 4.2.21 on 2025-12-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0042_contactorganization_datenschutz_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligungbeitrag',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Stellungnahme bestätigt'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Stellungnahme bestätigt'),
        ),
    ]
