# Generated by Django 4.2.21 on 2025-12-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0043_bplanbeteiligungbeitrag_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligungbeitrag',
            name='email',
            field=models.EmailField(default='demo@example.com', help_text='EMail-Adresse zur Bestätigung der Abgabe ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, verbose_name='E-Mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='email',
            field=models.EmailField(default='demo@example.com', help_text='EMail-Adresse zur Bestätigung der Abgabe ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, verbose_name='E-Mail'),
            preserve_default=False,
        ),
    ]
