# Generated by Django 4.2.21 on 2025-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0044_bplanbeteiligungbeitrag_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligungbeitrag',
            name='withdrawn',
            field=models.BooleanField(default=False, verbose_name='Stellungnahme zurückgezogen'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='withdrawn',
            field=models.BooleanField(default=False, verbose_name='Stellungnahme zurückgezogen'),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligungbeitrag',
            name='email',
            field=models.EmailField(help_text='EMail-Adresse zur Bestätigung der Abgabe Ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, verbose_name='EMail'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='email',
            field=models.EmailField(help_text='EMail-Adresse zur Bestätigung der Abgabe Ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, verbose_name='EMail'),
        ),
    ]
