# Generated by Django 4.2.21 on 2025-12-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_clamd.validators
import formset.richtext.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0045_bplanbeteiligungbeitrag_withdrawn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPlanBeteiligungBeitrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('titel', models.CharField(help_text='Geben Sie hier bitte einen aussagekräftigen Titel für Ihren Beitrag an.', max_length=300, verbose_name='Titel des Beitrags')),
                ('beschreibung', formset.richtext.fields.RichTextField(verbose_name='Beitrag / Kommentar (Textform)')),
                ('approved', models.BooleanField(default=False, verbose_name='Stellungnahme bestätigt')),
                ('email', models.EmailField(help_text='EMail-Adresse zur Bestätigung der Abgabe Ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, verbose_name='EMail')),
                ('withdrawn', models.BooleanField(default=False, verbose_name='Stellungnahme zurückgezogen')),
                ('bplan_beteiligung', simple_history.models.HistoricForeignKey(help_text='BPlanBeteiligung', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='xplanung_light.fplanbeteiligung', verbose_name='BPlanBeteiligung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bplanspezexternereferenz',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads', validators=[django_clamd.validators.validate_file_infection], verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='fplanspezexternereferenz',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads', validators=[django_clamd.validators.validate_file_infection], verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='historicalbplanspezexternereferenz',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django_clamd.validators.validate_file_infection], verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='historicalfplanspezexternereferenz',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django_clamd.validators.validate_file_infection], verbose_name='Dokument'),
        ),
        migrations.CreateModel(
            name='HistoricalFPlanBeteiligungBeitragAnhang',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=256)),
                ('typ', models.CharField(choices=[('1000', 'Beschreibung'), ('2000', 'Foto'), ('3000', 'Karte/Skizze')], db_index=True, default='1000', help_text='Typ / Inhalt des Anhngs zum Kommentar', max_length=5, verbose_name='Typ / Inhalt des Anhangs')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dokument')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beitrag', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='Dateianhänge zum Beitrag / Kommentar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplanbeteiligungbeitrag', verbose_name='Anlage zum Beitrag / Kommentar')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical f plan beteiligung beitrag anhang',
                'verbose_name_plural': 'historical f plan beteiligung beitrag anhangs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFPlanBeteiligungBeitrag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('titel', models.CharField(help_text='Geben Sie hier bitte einen aussagekräftigen Titel für Ihren Beitrag an.', max_length=300, verbose_name='Titel des Beitrags')),
                ('beschreibung', formset.richtext.fields.RichTextField(verbose_name='Beitrag / Kommentar (Textform)')),
                ('approved', models.BooleanField(default=False, verbose_name='Stellungnahme bestätigt')),
                ('email', models.EmailField(help_text='EMail-Adresse zur Bestätigung der Abgabe Ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, verbose_name='EMail')),
                ('withdrawn', models.BooleanField(default=False, verbose_name='Stellungnahme zurückgezogen')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bplan_beteiligung', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='BPlanBeteiligung', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplanbeteiligung', verbose_name='BPlanBeteiligung')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical f plan beteiligung beitrag',
                'verbose_name_plural': 'historical f plan beteiligung beitrags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FPlanBeteiligungBeitragAnhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=256)),
                ('typ', models.CharField(choices=[('1000', 'Beschreibung'), ('2000', 'Foto'), ('3000', 'Karte/Skizze')], db_index=True, default='1000', help_text='Typ / Inhalt des Anhngs zum Kommentar', max_length=5, verbose_name='Typ / Inhalt des Anhangs')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Dokument')),
                ('beitrag', simple_history.models.HistoricForeignKey(help_text='Dateianhänge zum Beitrag / Kommentar', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='xplanung_light.fplanbeteiligungbeitrag', verbose_name='Anlage zum Beitrag / Kommentar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
