# Generated by Django 4.2.21 on 2026-02-04 15:38

from django.db import migrations, models
import django_clamd.validators


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0047_alter_bplan_xplan_gml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplan',
            name='xplan_gml',
            field=models.TextField(blank=True, null=True, verbose_name='XPlan GML-Dokument'),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligungbeitraganhang',
            name='attachment',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='uploads', verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='bplanspezexternereferenz',
            name='attachment',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='uploads', validators=[django_clamd.validators.validate_file_infection], verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='fplan',
            name='xplan_gml',
            field=models.TextField(blank=True, null=True, verbose_name='XPlan GML-Dokument'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligungbeitraganhang',
            name='attachment',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='uploads', verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='fplanspezexternereferenz',
            name='attachment',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='uploads', validators=[django_clamd.validators.validate_file_infection], verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='historicalbplan',
            name='xplan_gml',
            field=models.TextField(blank=True, null=True, verbose_name='XPlan GML-Dokument'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitraganhang',
            name='attachment',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='historicalbplanspezexternereferenz',
            name='attachment',
            field=models.TextField(blank=True, max_length=1024, null=True, validators=[django_clamd.validators.validate_file_infection], verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='historicalfplan',
            name='xplan_gml',
            field=models.TextField(blank=True, null=True, verbose_name='XPlan GML-Dokument'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligungbeitraganhang',
            name='attachment',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='historicalfplanspezexternereferenz',
            name='attachment',
            field=models.TextField(blank=True, max_length=1024, null=True, validators=[django_clamd.validators.validate_file_infection], verbose_name='Dokument'),
        ),
    ]
