# Generated by Django 4.2.21 on 2026-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0049_historicalrequestfororganizationadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfororganizationadmin',
            name='organizations',
            field=models.ManyToManyField(to='xplanung_light.administrativeorganization', verbose_name='Gebietskörperschaft(en)'),
        ),
    ]
