# Generated by Django 4.2.21 on 2026-02-09 09:36

from django.db import migrations, models
import formset.richtext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0050_alter_requestfororganizationadmin_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestfororganizationadmin',
            name='delete_reason',
            field=models.CharField(blank=True, choices=[('c', 'Bestätigt'), ('r', 'Zurückgewiesen')], default='1000', help_text='Grund für die Löschung des Antrags', max_length=1, null=True, verbose_name='Grund für die Löschung'),
        ),
        migrations.AddField(
            model_name='historicalrequestfororganizationadmin',
            name='refuse_reason',
            field=formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Begründung für die Ablehnung des Antrags'),
        ),
        migrations.AddField(
            model_name='requestfororganizationadmin',
            name='delete_reason',
            field=models.CharField(blank=True, choices=[('c', 'Bestätigt'), ('r', 'Zurückgewiesen')], default='1000', help_text='Grund für die Löschung des Antrags', max_length=1, null=True, verbose_name='Grund für die Löschung'),
        ),
        migrations.AddField(
            model_name='requestfororganizationadmin',
            name='refuse_reason',
            field=formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Begründung für die Ablehnung des Antrags'),
        ),
        migrations.AlterField(
            model_name='requestfororganizationadmin',
            name='organizations',
            field=models.ManyToManyField(related_name='pending_admin_requests', to='xplanung_light.administrativeorganization', verbose_name='Gebietskörperschaft(en)'),
        ),
    ]
