# Generated by Django 4.2.21 on 2026-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0051_historicalrequestfororganizationadmin_delete_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestfororganizationadmin',
            name='refuse_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Begründung für die Ablehnung des Antrags'),
        ),
        migrations.AlterField(
            model_name='requestfororganizationadmin',
            name='refuse_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Begründung für die Ablehnung des Antrags'),
        ),
    ]
