# Generated by Django 4.2.21 on 2026-02-09 15:52

from django.db import migrations
import formset.richtext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0052_alter_historicalrequestfororganizationadmin_refuse_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequestfororganizationadmin',
            name='refuse_reason',
        ),
        migrations.RemoveField(
            model_name='requestfororganizationadmin',
            name='refuse_reason',
        ),
        migrations.AddField(
            model_name='historicalrequestfororganizationadmin',
            name='editing_note',
            field=formset.richtext.fields.RichTextField(default='{}', verbose_name='Begründung für die Ablehnung des Antrags'),
        ),
        migrations.AddField(
            model_name='requestfororganizationadmin',
            name='editing_note',
            field=formset.richtext.fields.RichTextField(default='{}', verbose_name='Begründung für die Ablehnung des Antrags'),
        ),
    ]
