# Generated by Django 4.2.21 on 2026-02-09 16:01

from django.db import migrations
import formset.richtext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0053_remove_historicalrequestfororganizationadmin_refuse_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestfororganizationadmin',
            name='editing_note',
            field=formset.richtext.fields.RichTextField(verbose_name='Begründung für die Ablehnung des Antrags'),
        ),
        migrations.AlterField(
            model_name='requestfororganizationadmin',
            name='editing_note',
            field=formset.richtext.fields.RichTextField(verbose_name='Begründung für die Ablehnung des Antrags'),
        ),
    ]
