# Generated by Django 4.2.21 on 2026-02-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0055_alter_historicalrequestfororganizationadmin_editing_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestfororganizationadmin',
            name='delete_reason',
            field=models.CharField(blank=True, choices=[('c', 'Bestätigt'), ('r', 'Zurückgewiesen')], help_text='Grund für die Löschung des Antrags', max_length=1, null=True, verbose_name='Grund für die Löschung'),
        ),
        migrations.AlterField(
            model_name='requestfororganizationadmin',
            name='delete_reason',
            field=models.CharField(blank=True, choices=[('c', 'Bestätigt'), ('r', 'Zurückgewiesen')], help_text='Grund für die Löschung des Antrags', max_length=1, null=True, verbose_name='Grund für die Löschung'),
        ),
    ]
