# Generated by Django 4.2.21 on 2026-02-25 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import formset.richtext.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0057_alter_historicalrequestfororganizationadmin_delete_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('commentator', 'Stellungnehmender'), ('manager', 'Planverwalter')], db_index=True, help_text='Rolle auf die die Einwilligungsoption anzuwenden ist.', max_length=15, verbose_name='Rolle')),
                ('title', models.CharField(help_text='Titel der Einwilligungsoption', max_length=300, verbose_name='Titel der Einwilligungsoption')),
                ('description', formset.richtext.fields.RichTextField(verbose_name='Einwilligungsoption (Text)')),
                ('valid_from', models.DateField(blank=True, help_text='Beginn der Gültigkeit der Einwilligungsoption', null=True, verbose_name='Gültig von')),
                ('valid_until', models.DateField(blank=True, help_text='Ende der Gültigkeit der Einwilligungsoption', null=True, verbose_name='Gültig bis')),
                ('opt_out', models.BooleanField(default=False, verbose_name='Vorausgewählt')),
                ('mandatory', models.BooleanField(default=False, verbose_name='Verpflichtend')),
                ('validity_period', models.IntegerField(blank=True, null=True, verbose_name='Gültigkeitsdauer in Tagen')),
                ('obsolete', models.BooleanField(default=False, verbose_name='Hinfällig')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consenting', models.BooleanField(default=False, verbose_name='Zugestimmt')),
                ('date', models.DateField(verbose_name='Datum der Zustimmung')),
                ('expires_on', models.DateField(verbose_name='Ablauf der Zustimmung')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xplanung_light.consentoption', verbose_name='Zustimmungsoption')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
        ),
    ]
