# Generated by Django 4.2.21 on 2026-02-25 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import formset.richtext.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0058_consentoption_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='consenting',
            field=models.BooleanField(default=False, verbose_name='Eingewilligt'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='date',
            field=models.DateField(verbose_name='Datum der Einwilligung'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='expires_on',
            field=models.DateField(verbose_name='Ablauf der Einwilligung'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='option',
            field=simple_history.models.HistoricForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xplanung_light.consentoption', verbose_name='Einwilligungsoption'),
        ),
        migrations.CreateModel(
            name='HistoricalConsentOption',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('commentator', 'Stellungnehmender'), ('manager', 'Planverwalter')], db_index=True, help_text='Rolle auf die die Einwilligungsoption anzuwenden ist.', max_length=15, verbose_name='Rolle')),
                ('title', models.CharField(help_text='Titel der Einwilligungsoption', max_length=300, verbose_name='Titel der Einwilligungsoption')),
                ('description', formset.richtext.fields.RichTextField(verbose_name='Einwilligungsoption (Text)')),
                ('valid_from', models.DateField(blank=True, help_text='Beginn der Gültigkeit der Einwilligungsoption', null=True, verbose_name='Gültig von')),
                ('valid_until', models.DateField(blank=True, help_text='Ende der Gültigkeit der Einwilligungsoption', null=True, verbose_name='Gültig bis')),
                ('opt_out', models.BooleanField(default=False, verbose_name='Vorausgewählt')),
                ('mandatory', models.BooleanField(default=False, verbose_name='Verpflichtend')),
                ('validity_period', models.IntegerField(blank=True, null=True, verbose_name='Gültigkeitsdauer in Tagen')),
                ('obsolete', models.BooleanField(default=False, verbose_name='Hinfällig')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical consent option',
                'verbose_name_plural': 'historical consent options',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
