# Generated by Django 4.2.21 on 2026-02-26 11:22

from django.db import migrations
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0059_alter_consent_consenting_alter_consent_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fplanbeteiligungbeitrag',
            name='bplan_beteiligung',
        ),
        migrations.RemoveField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='bplan_beteiligung',
        ),
        migrations.AddField(
            model_name='fplanbeteiligungbeitrag',
            name='fplan_beteiligung',
            field=simple_history.models.HistoricForeignKey(help_text='FPlanBeteiligung', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='xplanung_light.fplanbeteiligung', verbose_name='FPlanBeteiligung'),
        ),
        migrations.AddField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='fplan_beteiligung',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='FPlanBeteiligung', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplanbeteiligung', verbose_name='FPlanBeteiligung'),
        ),
    ]
