# Generated by Django 4.2.21 on 2026-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0060_remove_fplanbeteiligungbeitrag_bplan_beteiligung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentoption',
            name='type',
            field=models.CharField(choices=[('commentator', 'Stellungnehmender'), ('manager', 'Planverwalter'), ('application', 'Gesamte Anwendung')], db_index=True, help_text='Rolle auf die die Einwilligungsoption anzuwenden ist.', max_length=15, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='historicalconsentoption',
            name='type',
            field=models.CharField(choices=[('commentator', 'Stellungnehmender'), ('manager', 'Planverwalter'), ('application', 'Gesamte Anwendung')], db_index=True, help_text='Rolle auf die die Einwilligungsoption anzuwenden ist.', max_length=15, verbose_name='Rolle'),
        ),
    ]
