# Generated by Django 4.2.21 on 2026-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0061_alter_consentoption_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplan',
            name='rechtsstand',
            field=models.CharField(blank=True, choices=[('1000', 'Austellungsbeschluss'), ('2000', 'ImVerfahren'), ('3000', 'Satzung'), ('4000', 'InKraftGetreten'), ('5000', 'Untergegangen')], db_index=True, default='1000', help_text='Rechtsstand des Bebauungsplans - wird automatisch aus den Datumsfeldern ermittelt!', max_length=5, null=True, verbose_name='Rechtsstand des Bebauungsplans'),
        ),
        migrations.AddField(
            model_name='historicalbplan',
            name='rechtsstand',
            field=models.CharField(blank=True, choices=[('1000', 'Austellungsbeschluss'), ('2000', 'ImVerfahren'), ('3000', 'Satzung'), ('4000', 'InKraftGetreten'), ('5000', 'Untergegangen')], db_index=True, default='1000', help_text='Rechtsstand des Bebauungsplans - wird automatisch aus den Datumsfeldern ermittelt!', max_length=5, null=True, verbose_name='Rechtsstand des Bebauungsplans'),
        ),
    ]
