# Generated by Django 4.2.21 on 2026-03-20 16:16

from django.db import migrations, models
import formset.richtext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0062_bplan_rechtsstand_historicalbplan_rechtsstand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bplan',
            name='rechtsstand',
        ),
        migrations.RemoveField(
            model_name='historicalbplan',
            name='rechtsstand',
        ),
        migrations.AlterField(
            model_name='administrativeorganization',
            name='published_data_accessrights',
            field=models.CharField(blank=True, help_text='Angaben zu vorhandenen Zugriffsbeschränkungen (ist beispielsweise der Zugriff für jedermann möglich, oder nur für besonders berechtigte Personengruppen)', max_length=4096, null=True, verbose_name='Zugriffsbeschränkungen'),
        ),
        migrations.AlterField(
            model_name='administrativeorganization',
            name='published_data_license_source_note',
            field=models.CharField(blank=True, help_text='Art der Quellenangabe - falls Lizenz diese erfordert', max_length=4096, null=True, verbose_name='Quellenangabe'),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeorganization',
            name='published_data_accessrights',
            field=models.CharField(blank=True, help_text='Angaben zu vorhandenen Zugriffsbeschränkungen (ist beispielsweise der Zugriff für jedermann möglich, oder nur für besonders berechtigte Personengruppen)', max_length=4096, null=True, verbose_name='Zugriffsbeschränkungen'),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeorganization',
            name='published_data_license_source_note',
            field=models.CharField(blank=True, help_text='Art der Quellenangabe - falls Lizenz diese erfordert', max_length=4096, null=True, verbose_name='Quellenangabe'),
        ),
        migrations.AlterField(
            model_name='historicalrequestfororganizationadmin',
            name='editing_note',
            field=formset.richtext.fields.RichTextField(null=True, verbose_name='Begründung für die Ablehnung des Antrags bzw. Hinweise zur Freigabe - wie wurde Antragsteller kontaktiert/geprüft. Bei Ablehnung bekommt der Antragsteller die Begründung als Mail zugestellt!'),
        ),
        migrations.AlterField(
            model_name='historicaluvp',
            name='typ',
            field=models.CharField(blank=True, choices=[('18.1: Feriendorf Außenbereich', (('18_1_1', '18.1.1 (X): Betten >= 300 oder GZ >= 200'), ('18_1_2', '18.1.2 (A): Betten >= 100 < 300 oder GZ >=80 < 200'))), ('18.2: Campingplatz Außenbereich', (('18_2_1', '18.2.1 (X): StPl 200+'), ('18_2_2', '18.2.2 (A): StPl >=50 < 200'))), ('18.3: Freizeitpark Außenbereich', (('18_3_1', '18.3.1 (X):  F > 10ha'), ('18_3_2', '18.3.2 (A): 4ha < F < 10ha'))), ('18.4: Parkplatz Außenbereich', (('18_4_1', '18.4.1 (X): F > 1ha'), ('18_4_2', '18.4.2 (A): 0,5ha < F < 1ha'))), ('18.5: Industriezone Außenbereich', (('18_5_1', '18.5.1 (X): F > 100.000m^2'), ('18_5_2', '18.5.2 (A): 20.000m^2 < F < 100.000m^2'))), ('18.6: Einkaufszentrums Außenbereich', (('18_6_1', '18.6.1 (X): F > 5.000m^2'), ('18_6_2', '18.6.2 (A): 1.200m^2 < F < 5.000m^2'))), ('18.7: BPlan Außenbereich', (('18_7_1', '18.7.1 (X): F > 100.000m^2'), ('18_7_2', '18.7.2 (A): 20.000m^2 < F < 100.000m^2'))), ('Andere', (('18_8', '18.8 (A): Vorhaben gem 18.1-18.7 - Nichtaußenbereich'), ('18_9', '18.9: Vorgesehene UVP - Zulässigkeit gem. BPlan')))], db_index=True, help_text='Kategorie für Bauvorhaben gem. Anlage 1 UVPG - https://www.gesetze-im-internet.de/uvpg/anlage_1.html', max_length=7, null=True, verbose_name='Kategorie für Bauvorhaben gem. Anlage 1 UVPG'),
        ),
        migrations.AlterField(
            model_name='requestfororganizationadmin',
            name='editing_note',
            field=formset.richtext.fields.RichTextField(null=True, verbose_name='Begründung für die Ablehnung des Antrags bzw. Hinweise zur Freigabe - wie wurde Antragsteller kontaktiert/geprüft. Bei Ablehnung bekommt der Antragsteller die Begründung als Mail zugestellt!'),
        ),
        migrations.AlterField(
            model_name='uvp',
            name='typ',
            field=models.CharField(blank=True, choices=[('18.1: Feriendorf Außenbereich', (('18_1_1', '18.1.1 (X): Betten >= 300 oder GZ >= 200'), ('18_1_2', '18.1.2 (A): Betten >= 100 < 300 oder GZ >=80 < 200'))), ('18.2: Campingplatz Außenbereich', (('18_2_1', '18.2.1 (X): StPl 200+'), ('18_2_2', '18.2.2 (A): StPl >=50 < 200'))), ('18.3: Freizeitpark Außenbereich', (('18_3_1', '18.3.1 (X):  F > 10ha'), ('18_3_2', '18.3.2 (A): 4ha < F < 10ha'))), ('18.4: Parkplatz Außenbereich', (('18_4_1', '18.4.1 (X): F > 1ha'), ('18_4_2', '18.4.2 (A): 0,5ha < F < 1ha'))), ('18.5: Industriezone Außenbereich', (('18_5_1', '18.5.1 (X): F > 100.000m^2'), ('18_5_2', '18.5.2 (A): 20.000m^2 < F < 100.000m^2'))), ('18.6: Einkaufszentrums Außenbereich', (('18_6_1', '18.6.1 (X): F > 5.000m^2'), ('18_6_2', '18.6.2 (A): 1.200m^2 < F < 5.000m^2'))), ('18.7: BPlan Außenbereich', (('18_7_1', '18.7.1 (X): F > 100.000m^2'), ('18_7_2', '18.7.2 (A): 20.000m^2 < F < 100.000m^2'))), ('Andere', (('18_8', '18.8 (A): Vorhaben gem 18.1-18.7 - Nichtaußenbereich'), ('18_9', '18.9: Vorgesehene UVP - Zulässigkeit gem. BPlan')))], db_index=True, help_text='Kategorie für Bauvorhaben gem. Anlage 1 UVPG - https://www.gesetze-im-internet.de/uvpg/anlage_1.html', max_length=7, null=True, verbose_name='Kategorie für Bauvorhaben gem. Anlage 1 UVPG'),
        ),
    ]
