# Generated by Django 4.2.21 on 2026-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0063_remove_bplan_rechtsstand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestfororganizationadmin',
            name='editing_note',
            field=models.TextField(null=True, verbose_name='Begründung für die Ablehnung des Antrags bzw. Hinweise zur Freigabe - wie wurde Antragsteller kontaktiert/geprüft. Bei Ablehnung bekommt der Antragsteller die Begründung als Mail zugestellt!'),
        ),
        migrations.AlterField(
            model_name='requestfororganizationadmin',
            name='editing_note',
            field=models.TextField(null=True, verbose_name='Begründung für die Ablehnung des Antrags bzw. Hinweise zur Freigabe - wie wurde Antragsteller kontaktiert/geprüft. Bei Ablehnung bekommt der Antragsteller die Begründung als Mail zugestellt!'),
        ),
    ]
