# Generated by Django 4.2.21 on 2026-04-14 07:18

from django.db import migrations, models
import django.db.models.deletion
import formset.richtext.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0064_alter_historicalrequestfororganizationadmin_editing_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestfororganizationadmin',
            name='editing_note',
            field=models.TextField(help_text='Begründung für die Ablehnung des Antrags bzw. Hinweise zur Freigabe - wie wurde Antragsteller kontaktiert/geprüft. Bei Ablehnung bekommt der Antragsteller die Begründung als Mail zugestellt!', null=True, verbose_name='Begründung'),
        ),
        migrations.AlterField(
            model_name='requestfororganizationadmin',
            name='editing_note',
            field=models.TextField(help_text='Begründung für die Ablehnung des Antrags bzw. Hinweise zur Freigabe - wie wurde Antragsteller kontaktiert/geprüft. Bei Ablehnung bekommt der Antragsteller die Begründung als Mail zugestellt!', null=True, verbose_name='Begründung'),
        ),
        migrations.CreateModel(
            name='FPlanBeitragStellungnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('bezug_beitrag', formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Auszug/Zitat aus Beitrag auf den sich die Stellungnahme bezieht')),
                ('stellungnahme', formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Textliche Stellungnahme der Verwaltung')),
                ('beruecksichtigung', models.JSONField(blank=True, default=list, verbose_name='Berücksichtigung in der Planung')),
                ('beitrag', simple_history.models.HistoricForeignKey(help_text='Stellungnahme der Verwaltung', on_delete=django.db.models.deletion.CASCADE, to='xplanung_light.fplanbeteiligungbeitrag', verbose_name='Stellungnahme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BPlanBeitragStellungnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('bezug_beitrag', formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Auszug/Zitat aus Beitrag auf den sich die Stellungnahme bezieht')),
                ('stellungnahme', formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Textliche Stellungnahme der Verwaltung')),
                ('beruecksichtigung', models.JSONField(blank=True, default=list, verbose_name='Berücksichtigung in der Planung')),
                ('beitrag', simple_history.models.HistoricForeignKey(help_text='Stellungnahme der Verwaltung', on_delete=django.db.models.deletion.CASCADE, to='xplanung_light.bplanbeteiligungbeitrag', verbose_name='Stellungnahme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
