# Generated by Django 4.2.21 on 2026-04-14 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import formset.richtext.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0065_alter_historicalrequestfororganizationadmin_editing_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFPlanBeitragStellungnahme',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('bezug_beitrag', formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Auszug/Zitat aus Beitrag auf den sich die Stellungnahme bezieht')),
                ('stellungnahme', formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Textliche Stellungnahme der Verwaltung')),
                ('beruecksichtigung', models.JSONField(blank=True, default=list, verbose_name='Berücksichtigung in der Planung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beitrag', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='Stellungnahme der Verwaltung', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplanbeteiligungbeitrag', verbose_name='Stellungnahme')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical f plan beitrag stellungnahme',
                'verbose_name_plural': 'historical f plan beitrag stellungnahmes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBPlanBeitragStellungnahme',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('bezug_beitrag', formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Auszug/Zitat aus Beitrag auf den sich die Stellungnahme bezieht')),
                ('stellungnahme', formset.richtext.fields.RichTextField(blank=True, null=True, verbose_name='Textliche Stellungnahme der Verwaltung')),
                ('beruecksichtigung', models.JSONField(blank=True, default=list, verbose_name='Berücksichtigung in der Planung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beitrag', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='Stellungnahme der Verwaltung', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.bplanbeteiligungbeitrag', verbose_name='Stellungnahme')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical b plan beitrag stellungnahme',
                'verbose_name_plural': 'historical b plan beitrag stellungnahmes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
