# Generated by Django 4.2.21 on 2026-04-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0066_historicalfplanbeitragstellungnahme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bplanbeitragstellungnahme',
            old_name='beruecksichtigung',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='fplanbeitragstellungnahme',
            old_name='beruecksichtigung',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='historicalbplanbeitragstellungnahme',
            old_name='beruecksichtigung',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='historicalfplanbeitragstellungnahme',
            old_name='beruecksichtigung',
            new_name='tags',
        ),
    ]
