# Generated by Django 4.2.21 on 2026-04-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0067_rename_beruecksichtigung_bplanbeitragstellungnahme_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bplanbeitragstellungnahme',
            old_name='tags',
            new_name='beruecksichtigung',
        ),
        migrations.RenameField(
            model_name='fplanbeitragstellungnahme',
            old_name='tags',
            new_name='beruecksichtigung',
        ),
        migrations.RenameField(
            model_name='historicalbplanbeitragstellungnahme',
            old_name='tags',
            new_name='beruecksichtigung',
        ),
        migrations.RenameField(
            model_name='historicalfplanbeitragstellungnahme',
            old_name='tags',
            new_name='beruecksichtigung',
        ),
    ]
