# Generated by Django 4.2.21 on 2026-04-17 12:45

from django.db import migrations, models
import django.db.models.deletion
import formset.richtext.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0068_rename_tags_bplanbeitragstellungnahme_beruecksichtigung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligungbeitrag',
            name='name',
            field=models.CharField(blank=True, help_text='Name der Person oder Institution die den Beitrag einreicht', max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='bplanbeteiligungbeitrag',
            name='typ',
            field=models.CharField(choices=[('1000', 'Online'), ('2000', 'EMail'), ('3000', 'Schriftlich'), ('4000', 'Niederschrift')], db_index=True, default='1000', help_text='Typ des Beitrags zum Kommentar', max_length=5, verbose_name='Typ des Beitrags'),
        ),
        migrations.AddField(
            model_name='fplanbeteiligungbeitrag',
            name='name',
            field=models.CharField(blank=True, help_text='Name der Person oder Institution die den Beitrag einreicht', max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='fplanbeteiligungbeitrag',
            name='typ',
            field=models.CharField(choices=[('1000', 'Online'), ('2000', 'EMail'), ('3000', 'Schriftlich'), ('4000', 'Niederschrift')], db_index=True, default='1000', help_text='Typ des Beitrags zum Kommentar', max_length=5, verbose_name='Typ des Beitrags'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='name',
            field=models.CharField(blank=True, help_text='Name der Person oder Institution die den Beitrag einreicht', max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='typ',
            field=models.CharField(choices=[('1000', 'Online'), ('2000', 'EMail'), ('3000', 'Schriftlich'), ('4000', 'Niederschrift')], db_index=True, default='1000', help_text='Typ des Beitrags zum Kommentar', max_length=5, verbose_name='Typ des Beitrags'),
        ),
        migrations.AddField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='name',
            field=models.CharField(blank=True, help_text='Name der Person oder Institution die den Beitrag einreicht', max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='typ',
            field=models.CharField(choices=[('1000', 'Online'), ('2000', 'EMail'), ('3000', 'Schriftlich'), ('4000', 'Niederschrift')], db_index=True, default='1000', help_text='Typ des Beitrags zum Kommentar', max_length=5, verbose_name='Typ des Beitrags'),
        ),
        migrations.AlterField(
            model_name='bplanbeitragstellungnahme',
            name='beitrag',
            field=simple_history.models.HistoricForeignKey(help_text='Stellungnahme der Verwaltung', on_delete=django.db.models.deletion.CASCADE, related_name='stellungnahmen', to='xplanung_light.bplanbeteiligungbeitrag', verbose_name='Stellungnahme'),
        ),
        migrations.AlterField(
            model_name='bplanbeitragstellungnahme',
            name='beruecksichtigung',
            field=models.JSONField(blank=True, default=list, help_text='Berücksichtigung in der Planung', verbose_name='Berücksichtigung'),
        ),
        migrations.AlterField(
            model_name='bplanbeitragstellungnahme',
            name='bezug_beitrag',
            field=formset.richtext.fields.RichTextField(blank=True, help_text='Auszug/Zitat/Referenz aus Beitrag auf den sich die Stellungnahme bezieht', null=True, verbose_name='Bezug'),
        ),
        migrations.AlterField(
            model_name='bplanbeitragstellungnahme',
            name='stellungnahme',
            field=formset.richtext.fields.RichTextField(blank=True, help_text='Textliche Stellungnahme der Verwaltung', null=True, verbose_name='Stellungnahme'),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligungbeitrag',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Beitrag bestätigt'),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligungbeitrag',
            name='withdrawn',
            field=models.BooleanField(default=False, verbose_name='Beitrag zurückgezogen'),
        ),
        migrations.AlterField(
            model_name='fplanbeitragstellungnahme',
            name='beitrag',
            field=simple_history.models.HistoricForeignKey(help_text='Stellungnahme der Verwaltung', on_delete=django.db.models.deletion.CASCADE, related_name='stellungnahmen', to='xplanung_light.fplanbeteiligungbeitrag', verbose_name='Stellungnahme'),
        ),
        migrations.AlterField(
            model_name='fplanbeitragstellungnahme',
            name='beruecksichtigung',
            field=models.JSONField(blank=True, default=list, help_text='Berücksichtigung in der Planung', verbose_name='Berücksichtigung'),
        ),
        migrations.AlterField(
            model_name='fplanbeitragstellungnahme',
            name='bezug_beitrag',
            field=formset.richtext.fields.RichTextField(blank=True, help_text='Auszug/Zitat/Referenz aus Beitrag auf den sich die Stellungnahme bezieht', null=True, verbose_name='Bezug'),
        ),
        migrations.AlterField(
            model_name='fplanbeitragstellungnahme',
            name='stellungnahme',
            field=formset.richtext.fields.RichTextField(blank=True, help_text='Textliche Stellungnahme der Verwaltung', null=True, verbose_name='Stellungnahme'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligungbeitrag',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Beitrag bestätigt'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligungbeitrag',
            name='withdrawn',
            field=models.BooleanField(default=False, verbose_name='Beitrag zurückgezogen'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeitragstellungnahme',
            name='beruecksichtigung',
            field=models.JSONField(blank=True, default=list, help_text='Berücksichtigung in der Planung', verbose_name='Berücksichtigung'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeitragstellungnahme',
            name='bezug_beitrag',
            field=formset.richtext.fields.RichTextField(blank=True, help_text='Auszug/Zitat/Referenz aus Beitrag auf den sich die Stellungnahme bezieht', null=True, verbose_name='Bezug'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeitragstellungnahme',
            name='stellungnahme',
            field=formset.richtext.fields.RichTextField(blank=True, help_text='Textliche Stellungnahme der Verwaltung', null=True, verbose_name='Stellungnahme'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Beitrag bestätigt'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='withdrawn',
            field=models.BooleanField(default=False, verbose_name='Beitrag zurückgezogen'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeitragstellungnahme',
            name='beruecksichtigung',
            field=models.JSONField(blank=True, default=list, help_text='Berücksichtigung in der Planung', verbose_name='Berücksichtigung'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeitragstellungnahme',
            name='bezug_beitrag',
            field=formset.richtext.fields.RichTextField(blank=True, help_text='Auszug/Zitat/Referenz aus Beitrag auf den sich die Stellungnahme bezieht', null=True, verbose_name='Bezug'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeitragstellungnahme',
            name='stellungnahme',
            field=formset.richtext.fields.RichTextField(blank=True, help_text='Textliche Stellungnahme der Verwaltung', null=True, verbose_name='Stellungnahme'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Beitrag bestätigt'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='withdrawn',
            field=models.BooleanField(default=False, verbose_name='Beitrag zurückgezogen'),
        ),
    ]
