# Generated by Django 4.2.21 on 2026-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0069_bplanbeteiligungbeitrag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplanbeteiligungbeitrag',
            name='typ',
            field=models.CharField(choices=[('1000', 'Online'), ('2000', 'E-Mail'), ('3000', 'Schriftlich'), ('4000', 'Niederschrift')], db_index=True, default='1000', help_text='Art der Einreichung des Beitrags / Kommentars', max_length=5, verbose_name='Einreichung'),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligungbeitraganhang',
            name='typ',
            field=models.CharField(choices=[('1000', 'Beschreibung'), ('2000', 'Foto'), ('3000', 'Karte/Skizze')], db_index=True, default='1000', help_text='Typ / Inhalt des Anhangs zum Kommentar', max_length=5, verbose_name='Typ / Inhalt des Anhangs'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligungbeitrag',
            name='typ',
            field=models.CharField(choices=[('1000', 'Online'), ('2000', 'E-Mail'), ('3000', 'Schriftlich'), ('4000', 'Niederschrift')], db_index=True, default='1000', help_text='Art der Einreichung des Beitrags / Kommentars', max_length=5, verbose_name='Einreichung'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligungbeitraganhang',
            name='typ',
            field=models.CharField(choices=[('1000', 'Beschreibung'), ('2000', 'Foto'), ('3000', 'Karte/Skizze')], db_index=True, default='1000', help_text='Typ / Inhalt des Anhangs zum Kommentar', max_length=5, verbose_name='Typ / Inhalt des Anhangs'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='typ',
            field=models.CharField(choices=[('1000', 'Online'), ('2000', 'E-Mail'), ('3000', 'Schriftlich'), ('4000', 'Niederschrift')], db_index=True, default='1000', help_text='Art der Einreichung des Beitrags / Kommentars', max_length=5, verbose_name='Einreichung'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitraganhang',
            name='typ',
            field=models.CharField(choices=[('1000', 'Beschreibung'), ('2000', 'Foto'), ('3000', 'Karte/Skizze')], db_index=True, default='1000', help_text='Typ / Inhalt des Anhangs zum Kommentar', max_length=5, verbose_name='Typ / Inhalt des Anhangs'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='typ',
            field=models.CharField(choices=[('1000', 'Online'), ('2000', 'E-Mail'), ('3000', 'Schriftlich'), ('4000', 'Niederschrift')], db_index=True, default='1000', help_text='Art der Einreichung des Beitrags / Kommentars', max_length=5, verbose_name='Einreichung'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligungbeitraganhang',
            name='typ',
            field=models.CharField(choices=[('1000', 'Beschreibung'), ('2000', 'Foto'), ('3000', 'Karte/Skizze')], db_index=True, default='1000', help_text='Typ / Inhalt des Anhangs zum Kommentar', max_length=5, verbose_name='Typ / Inhalt des Anhangs'),
        ),
    ]
