# Generated by Django 4.2.21 on 2026-04-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0070_alter_bplanbeteiligungbeitrag_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplanbeteiligungbeitrag',
            name='email',
            field=models.EmailField(blank=True, help_text='EMail-Adresse zur Bestätigung der Abgabe Ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, null=True, verbose_name='EMail'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligungbeitrag',
            name='email',
            field=models.EmailField(blank=True, help_text='EMail-Adresse zur Bestätigung der Abgabe Ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, null=True, verbose_name='EMail'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='email',
            field=models.EmailField(blank=True, help_text='EMail-Adresse zur Bestätigung der Abgabe Ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, null=True, verbose_name='EMail'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='email',
            field=models.EmailField(blank=True, help_text='EMail-Adresse zur Bestätigung der Abgabe Ihrer Stellungnahme. Sie bekommen eine Aktivierungsmail geschickt.', max_length=254, null=True, verbose_name='EMail'),
        ),
    ]
