# Generated by Django 4.2.21 on 2026-05-12 12:09

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0071_alter_bplanbeteiligungbeitrag_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalToebUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(help_text='Offizieller Name der Institution / Regionalstelle - z.B. Regionalstelle Wasserwirtschaft, Abfallwirtschaft, Bodenschutz', max_length=2048, verbose_name='Name der Institution / Regionalstelle')),
                ('description', models.TextField(blank=True, help_text='Erläuterung des Aufgabenbereichs - z.B. Erlaubnisse/Bewilligungen nach § 8, 9 WHG, ... ', null=True, verbose_name='Beschreibung des Aufgabenbereichs')),
                ('theme', models.CharField(choices=[('AB', 'Abfallentsorgung'), ('AG_ST', 'Agrarstruktur'), ('AM', 'Arbeitsmarkt'), ('BA', 'Bauaufsicht'), ('BGB', 'Bergbau, Geologie und Bodenschätze'), ('BSAL', 'Bodenschutz, Altlasten'), ('BS', 'Brandschutz'), ('DSP', 'Denkmalschutz, Denkmalpflege'), ('F', 'Fischerei'), ('FB', 'Flurbereinigung'), ('FW', 'Forst- und Waldwesen'), ('GS', 'Gesundheitspflege und Sozialwesen'), ('GHHI', 'Gewerbe, Handel, Handwerk und Industrie'), ('GDSS', 'Gottesdienst und Seelsorge'), ('GBOEH', 'Grundbesitz der öffentlichen Hand'), ('HS', 'Hochschulen'), ('IS', 'Immissionsschutz'), ('JW', 'Jagdwesen'), ('KV', 'Kataster- und Vermessungswesen'), ('KS', 'Katastrophenschutz'), ('KJH', 'Kinder- und Jugendhilfen'), ('KLA', 'Klimaanpassung'), ('KLS', 'Klimaschutz'), ('LW', 'Landwirtschaft'), ('NSLP', 'Naturschutz und Landschaftspflege'), ('OESO', 'Öffentliche Sicherheit und Ordnung'), ('PW', 'Postwesen'), ('RO', 'Raumordnung'), ('SW', 'Schulwesen'), ('SP', 'Sport'), ('STS', 'Strahlenschutz'), ('TK', 'Telekommunikation'), ('TOU', 'Tourismus'), ('UNVB', 'Umwelt und Naturschutzverbände'), ('UNVE', 'Umwelt- und Naturschutzvereinigungen'), ('VE', 'Ver- und Entsorgung (keine TK)'), ('VK', 'Verkehr'), ('VT', 'Verteidigung'), ('VW', 'Veterinärwesen'), ('WE', 'Welterbe'), ('OTH', 'Sonstige')], db_index=True, default='OTH', max_length=5, verbose_name='Thematische Zuordnung')),
                ('email', models.EmailField(max_length=512, verbose_name='Offizielle EMail-Adresse')),
                ('public', models.BooleanField(default=False, help_text='Gibt an, ob Informationen über die frei verfügbaren Schnittstellen publiziert werden.', verbose_name='Öffentlich verfügbar')),
                ('internal', models.BooleanField(default=False, help_text='Kontakt wird nur intern verwendet.', verbose_name='Intern')),
                ('address_street', models.CharField(blank=True, help_text='Straße und Hausnummer / Postfach', max_length=1024, null=True, verbose_name='Straße mit Hausnummer / Postfach')),
                ('address_postcode', models.CharField(blank=True, help_text='Postleitzahl', max_length=5, null=True, verbose_name='Postleitzahl')),
                ('address_city', models.CharField(blank=True, max_length=256, null=True, verbose_name='Stadt')),
                ('address_phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='Telefon')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Zuständigkeitsbereich')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical toeb unit',
                'verbose_name_plural': 'historical toeb units',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='adminorgauser',
            name='is_toeb_reporter',
            field=models.BooleanField(default=False, verbose_name='Nutzer kann Stellungnahmen für TOEB-Einheiten dieser Organisation abgeben.'),
        ),
        migrations.AlterField(
            model_name='administrativeorganization',
            name='name',
            field=models.CharField(help_text='Offizieller Name der Gebietskörperschaft/Organisation - z.B. Rhein-Lahn-Kreis', max_length=1024, verbose_name='Name der Gebietskörperschaft/Organisation'),
        ),
        migrations.AlterField(
            model_name='administrativeorganization',
            name='type',
            field=models.CharField(choices=[('KR', 'Landkreis'), ('KFS', 'Kreisfreie Stadt'), ('VG', 'Verbandsgemeinde'), ('VFG', 'Verbandsfreie Gemeinde'), ('GE', 'Gemeinde/Stadt'), ('UK', 'unbekannt')], db_index=True, default='UK', max_length=3, verbose_name='Typ der Gebietskörperschaft/Organisation'),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeorganization',
            name='name',
            field=models.CharField(help_text='Offizieller Name der Gebietskörperschaft/Organisation - z.B. Rhein-Lahn-Kreis', max_length=1024, verbose_name='Name der Gebietskörperschaft/Organisation'),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeorganization',
            name='type',
            field=models.CharField(choices=[('KR', 'Landkreis'), ('KFS', 'Kreisfreie Stadt'), ('VG', 'Verbandsgemeinde'), ('VFG', 'Verbandsfreie Gemeinde'), ('GE', 'Gemeinde/Stadt'), ('UK', 'unbekannt')], db_index=True, default='UK', max_length=3, verbose_name='Typ der Gebietskörperschaft/Organisation'),
        ),
        migrations.CreateModel(
            name='ToebUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(help_text='Offizieller Name der Institution / Regionalstelle - z.B. Regionalstelle Wasserwirtschaft, Abfallwirtschaft, Bodenschutz', max_length=2048, verbose_name='Name der Institution / Regionalstelle')),
                ('description', models.TextField(blank=True, help_text='Erläuterung des Aufgabenbereichs - z.B. Erlaubnisse/Bewilligungen nach § 8, 9 WHG, ... ', null=True, verbose_name='Beschreibung des Aufgabenbereichs')),
                ('theme', models.CharField(choices=[('AB', 'Abfallentsorgung'), ('AG_ST', 'Agrarstruktur'), ('AM', 'Arbeitsmarkt'), ('BA', 'Bauaufsicht'), ('BGB', 'Bergbau, Geologie und Bodenschätze'), ('BSAL', 'Bodenschutz, Altlasten'), ('BS', 'Brandschutz'), ('DSP', 'Denkmalschutz, Denkmalpflege'), ('F', 'Fischerei'), ('FB', 'Flurbereinigung'), ('FW', 'Forst- und Waldwesen'), ('GS', 'Gesundheitspflege und Sozialwesen'), ('GHHI', 'Gewerbe, Handel, Handwerk und Industrie'), ('GDSS', 'Gottesdienst und Seelsorge'), ('GBOEH', 'Grundbesitz der öffentlichen Hand'), ('HS', 'Hochschulen'), ('IS', 'Immissionsschutz'), ('JW', 'Jagdwesen'), ('KV', 'Kataster- und Vermessungswesen'), ('KS', 'Katastrophenschutz'), ('KJH', 'Kinder- und Jugendhilfen'), ('KLA', 'Klimaanpassung'), ('KLS', 'Klimaschutz'), ('LW', 'Landwirtschaft'), ('NSLP', 'Naturschutz und Landschaftspflege'), ('OESO', 'Öffentliche Sicherheit und Ordnung'), ('PW', 'Postwesen'), ('RO', 'Raumordnung'), ('SW', 'Schulwesen'), ('SP', 'Sport'), ('STS', 'Strahlenschutz'), ('TK', 'Telekommunikation'), ('TOU', 'Tourismus'), ('UNVB', 'Umwelt und Naturschutzverbände'), ('UNVE', 'Umwelt- und Naturschutzvereinigungen'), ('VE', 'Ver- und Entsorgung (keine TK)'), ('VK', 'Verkehr'), ('VT', 'Verteidigung'), ('VW', 'Veterinärwesen'), ('WE', 'Welterbe'), ('OTH', 'Sonstige')], db_index=True, default='OTH', max_length=5, verbose_name='Thematische Zuordnung')),
                ('email', models.EmailField(max_length=512, verbose_name='Offizielle EMail-Adresse')),
                ('public', models.BooleanField(default=False, help_text='Gibt an, ob Informationen über die frei verfügbaren Schnittstellen publiziert werden.', verbose_name='Öffentlich verfügbar')),
                ('internal', models.BooleanField(default=False, help_text='Kontakt wird nur intern verwendet.', verbose_name='Intern')),
                ('address_street', models.CharField(blank=True, help_text='Straße und Hausnummer / Postfach', max_length=1024, null=True, verbose_name='Straße mit Hausnummer / Postfach')),
                ('address_postcode', models.CharField(blank=True, help_text='Postleitzahl', max_length=5, null=True, verbose_name='Postleitzahl')),
                ('address_city', models.CharField(blank=True, max_length=256, null=True, verbose_name='Stadt')),
                ('address_phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='Telefon')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Zuständigkeitsbereich')),
                ('editors', models.ManyToManyField(help_text='Sachbearbeiter', related_name='toeb_units', to='xplanung_light.adminorgauser', verbose_name='Sachbearbeiter')),
                ('organization', simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toebs', to='xplanung_light.administrativeorganization', verbose_name='Übergeordnete Organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalToebUnit_editors',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('adminorgauser', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.adminorgauser')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicaltoebunit')),
                ('toebunit', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.toebunit')),
            ],
            options={
                'verbose_name': 'HistoricalToebUnit_editors',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicaltoebunit',
            name='organization',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.administrativeorganization', verbose_name='Übergeordnete Organisation'),
        ),
    ]
