# Generated by Django 4.2.21 on 2026-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0072_historicaltoebunit_adminorgauser_is_toeb_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeorganization',
            name='type',
            field=models.CharField(choices=[('KR', 'Landkreis'), ('KFS', 'Kreisfreie Stadt'), ('VG', 'Verbandsgemeinde'), ('VFG', 'Verbandsfreie Gemeinde'), ('GE', 'Gemeinde/Stadt'), ('LB', 'Landesbehörde'), ('BB', 'Bundesbehörde'), ('NGO', 'Nichtregierungsorganisation'), ('EV', 'Eingetragener Verein'), ('UNT', 'Unternehmen'), ('UK', 'unbekannt')], db_index=True, default='UK', max_length=3, verbose_name='Typ der Gebietskörperschaft/Organisation'),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeorganization',
            name='type',
            field=models.CharField(choices=[('KR', 'Landkreis'), ('KFS', 'Kreisfreie Stadt'), ('VG', 'Verbandsgemeinde'), ('VFG', 'Verbandsfreie Gemeinde'), ('GE', 'Gemeinde/Stadt'), ('LB', 'Landesbehörde'), ('BB', 'Bundesbehörde'), ('NGO', 'Nichtregierungsorganisation'), ('EV', 'Eingetragener Verein'), ('UNT', 'Unternehmen'), ('UK', 'unbekannt')], db_index=True, default='UK', max_length=3, verbose_name='Typ der Gebietskörperschaft/Organisation'),
        ),
    ]
