# Generated by Django 4.2.21 on 2026-05-13 07:19

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0073_alter_administrativeorganization_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligung',
            name='assigned_toebs',
            field=models.ManyToManyField(help_text='Zugewiesene TOEBs', to='xplanung_light.toebunit', verbose_name='Zugewiesene TOEBs'),
        ),
        migrations.AddField(
            model_name='fplanbeteiligung',
            name='assigned_toebs',
            field=models.ManyToManyField(help_text='Zugewiesene TOEBs', to='xplanung_light.toebunit', verbose_name='Zugewiesene TOEBs'),
        ),
        migrations.CreateModel(
            name='HistoricalFPlanBeteiligung_assigned_toebs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('fplanbeteiligung', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplanbeteiligung')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicalfplanbeteiligung')),
                ('toebunit', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.toebunit')),
            ],
            options={
                'verbose_name': 'HistoricalFPlanBeteiligung_assigned_toebs',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBPlanBeteiligung_assigned_toebs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('bplanbeteiligung', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.bplanbeteiligung')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicalbplanbeteiligung')),
                ('toebunit', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.toebunit')),
            ],
            options={
                'verbose_name': 'HistoricalBPlanBeteiligung_assigned_toebs',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
