# Generated by Django 4.2.21 on 2026-05-18 13:41

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0074_bplanbeteiligung_assigned_toebs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligungbeitrag',
            name='toeb',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplanung_light.toebunit', verbose_name='Träger öffentlicher Belange'),
        ),
        migrations.AddField(
            model_name='fplanbeteiligungbeitrag',
            name='toeb',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplanung_light.toebunit', verbose_name='Träger öffentlicher Belange'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='toeb',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.toebunit', verbose_name='Träger öffentlicher Belange'),
        ),
        migrations.AddField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='toeb',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.toebunit', verbose_name='Träger öffentlicher Belange'),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligung',
            name='assigned_toebs',
            field=models.ManyToManyField(blank=True, help_text='Zugewiesene TOEBs', to='xplanung_light.toebunit', verbose_name='Zugewiesene TOEBs'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligung',
            name='assigned_toebs',
            field=models.ManyToManyField(blank=True, help_text='Zugewiesene TOEBs', to='xplanung_light.toebunit', verbose_name='Zugewiesene TOEBs'),
        ),
    ]
