# Generated by Django 4.2.21 on 2026-05-27 07:16

from django.db import migrations, models
import django.utils.timezone
import organizations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0075_bplanbeteiligungbeitrag_toeb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminorgaowner',
            options={'verbose_name': 'organization owner', 'verbose_name_plural': 'organization owners'},
        ),
        migrations.AlterModelOptions(
            name='adminorgauser',
            options={'ordering': ['organization', 'user'], 'verbose_name': 'organization user', 'verbose_name_plural': 'organization users'},
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='created',
            field=organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='modified',
            field=organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='administrativeorganization',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminorgaowner',
            name='created',
            field=organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='adminorgaowner',
            name='modified',
            field=organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='adminorgauser',
            name='created',
            field=organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='adminorgauser',
            name='modified',
            field=organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='created',
            field=organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='modified',
            field=organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='historicaladministrativeorganization',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
