# Generated by Django 4.2.21 on 2026-05-27 07:17

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    # Get your concrete model dynamically
    CustomOrganization = apps.get_model('xplanung_light', 'AdministrativeOrganization')
    
    for org in CustomOrganization.objects.all():
        # Append the ID to guarantee uniqueness across existing data
        org.slug = f"{slugify(org.name)}-{org.id}"
        org.save()

class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0076_alter_adminorgaowner_options_and_more'), # Must be your Step 1 migration
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]