# Generated by Django 4.2.21 on 2026-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0077_auto_20260527_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeorganization',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeorganization',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
