# Generated by Django 4.2.21 on 2026-05-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0079_alter_adminorgauser_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPlanBeteiligungToebNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('start', models.DateTimeField(help_text='Startzeit', verbose_name='Startzeit')),
                ('end', models.DateTimeField(blank=True, help_text='Abschlusszeit', null=True, verbose_name='Abschlusszeit')),
                ('message', models.CharField(blank=True, help_text='Zusätzlicher Hinweis für Benachrichtigungsmail', max_length=4096, null=True, verbose_name='Bemerkung')),
                ('bplanbeteiligung', simple_history.models.HistoricForeignKey(help_text='BPlan-Beteiligung', on_delete=django.db.models.deletion.CASCADE, related_name='bplan_beteiligung_notifications', to='xplanung_light.bplanbeteiligung', verbose_name='BPlan-Beteiligung')),
                ('selected_toebs', models.ManyToManyField(blank=True, help_text='Ausgewählte TOEBs', to='xplanung_light.toebunit', verbose_name='Ausgewählte TOEBs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FPlanBeteiligungToebNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('start', models.DateTimeField(help_text='Startzeit', verbose_name='Startzeit')),
                ('end', models.DateTimeField(blank=True, help_text='Abschlusszeit', null=True, verbose_name='Abschlusszeit')),
                ('message', models.CharField(blank=True, help_text='Zusätzlicher Hinweis für Benachrichtigungsmail', max_length=4096, null=True, verbose_name='Bemerkung')),
                ('fplanbeteiligung', simple_history.models.HistoricForeignKey(help_text='FPlan-Beteiligung', on_delete=django.db.models.deletion.CASCADE, related_name='fplan_beteiligung_notifications', to='xplanung_light.fplanbeteiligung', verbose_name='FPlan-Beteiligung')),
                ('selected_toebs', models.ManyToManyField(blank=True, help_text='Ausgewählte TOEBs', to='xplanung_light.toebunit', verbose_name='Ausgewählte TOEBs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalBPlanBeteiligungToebNotification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('start', models.DateTimeField(help_text='Startzeit', verbose_name='Startzeit')),
                ('end', models.DateTimeField(blank=True, help_text='Abschlusszeit', null=True, verbose_name='Abschlusszeit')),
                ('message', models.CharField(blank=True, help_text='Zusätzlicher Hinweis für Benachrichtigungsmail', max_length=4096, null=True, verbose_name='Bemerkung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bplanbeteiligung', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='BPlan-Beteiligung', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.bplanbeteiligung', verbose_name='BPlan-Beteiligung')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical b plan beteiligung toeb notification',
                'verbose_name_plural': 'historical b plan beteiligung toeb notifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFPlanBeteiligungToebNotification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('start', models.DateTimeField(help_text='Startzeit', verbose_name='Startzeit')),
                ('end', models.DateTimeField(blank=True, help_text='Abschlusszeit', null=True, verbose_name='Abschlusszeit')),
                ('message', models.CharField(blank=True, help_text='Zusätzlicher Hinweis für Benachrichtigungsmail', max_length=4096, null=True, verbose_name='Bemerkung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fplanbeteiligung', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, help_text='FPlan-Beteiligung', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplanbeteiligung', verbose_name='FPlan-Beteiligung')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical f plan beteiligung toeb notification',
                'verbose_name_plural': 'historical f plan beteiligung toeb notifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='administrativeorganization',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeorganization',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='HistoricalFPlanBeteiligungToebNotification_selected_toebs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('fplanbeteiligungtoebnotification', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplanbeteiligungtoebnotification')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicalfplanbeteiligungtoebnotification')),
                ('toebunit', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.toebunit')),
            ],
            options={
                'verbose_name': 'HistoricalFPlanBeteiligungToebNotification_selected_toebs',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBPlanBeteiligungToebNotification_selected_toebs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('bplanbeteiligungtoebnotification', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.bplanbeteiligungtoebnotification')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicalbplanbeteiligungtoebnotification')),
                ('toebunit', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.toebunit')),
            ],
            options={
                'verbose_name': 'HistoricalBPlanBeteiligungToebNotification_selected_toebs',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
