# Generated by Django 4.2.21 on 2026-05-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0080_bplanbeteiligungtoebnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligungtoebnotification',
            name='protcol',
            field=models.JSONField(blank=True, help_text='Protokoll im json-Format', null=True, verbose_name='Protokoll'),
        ),
        migrations.AddField(
            model_name='fplanbeteiligungtoebnotification',
            name='protcol',
            field=models.JSONField(blank=True, help_text='Protokoll im json-Format', null=True, verbose_name='Protokoll'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungtoebnotification',
            name='protcol',
            field=models.JSONField(blank=True, help_text='Protokoll im json-Format', null=True, verbose_name='Protokoll'),
        ),
        migrations.AddField(
            model_name='historicalfplanbeteiligungtoebnotification',
            name='protcol',
            field=models.JSONField(blank=True, help_text='Protokoll im json-Format', null=True, verbose_name='Protokoll'),
        ),
        migrations.AlterField(
            model_name='bplanbeteiligung',
            name='assigned_toebs',
            field=models.ManyToManyField(blank=True, help_text='Zugewiesene TOEBs', related_name='bplan_beteiligungen', to='xplanung_light.toebunit', verbose_name='Zugewiesene TOEBs'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligung',
            name='assigned_toebs',
            field=models.ManyToManyField(blank=True, help_text='Zugewiesene TOEBs', related_name='fplan_beteiligungen', to='xplanung_light.toebunit', verbose_name='Zugewiesene TOEBs'),
        ),
    ]
