# Generated by Django 4.2.21 on 2026-05-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0081_bplanbeteiligungtoebnotification_protcol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bplanbeteiligungtoebnotification',
            old_name='protcol',
            new_name='protocol',
        ),
        migrations.RenameField(
            model_name='fplanbeteiligungtoebnotification',
            old_name='protcol',
            new_name='protocol',
        ),
        migrations.RenameField(
            model_name='historicalbplanbeteiligungtoebnotification',
            old_name='protcol',
            new_name='protocol',
        ),
        migrations.RenameField(
            model_name='historicalfplanbeteiligungtoebnotification',
            old_name='protcol',
            new_name='protocol',
        ),
    ]
