# Generated by Django 4.2.21 on 2026-06-09 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0082_rename_protcol_bplanbeteiligungtoebnotification_protocol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRequestForRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('delete_reason', models.CharField(blank=True, choices=[('c', 'Bestätigt'), ('r', 'Zurückgewiesen')], help_text='Grund für die Löschung des Antrags', max_length=10, null=True, verbose_name='Grund für die Löschung')),
                ('role', models.CharField(choices=[('TR', 'TOEB-Reporter'), ('OA', 'Organisationsadministrator')], default='OA', help_text='Rolle des Nutzers in Bezug auf die Organisation', max_length=2, verbose_name='Rolle')),
                ('editing_note', models.TextField(help_text='Begründung für die Ablehnung des Antrags bzw. Hinweise zur Freigabe - wie wurde Antragsteller kontaktiert/geprüft. Bei Ablehnung bekommt der Antragsteller die Begründung als Mail zugestellt!', null=True, verbose_name='Begründung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owned_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical request for role',
                'verbose_name_plural': 'historical request for roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RequestForRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_reason', models.CharField(blank=True, choices=[('c', 'Bestätigt'), ('r', 'Zurückgewiesen')], help_text='Grund für die Löschung des Antrags', max_length=10, null=True, verbose_name='Grund für die Löschung')),
                ('role', models.CharField(choices=[('TR', 'TOEB-Reporter'), ('OA', 'Organisationsadministrator')], default='OA', help_text='Rolle des Nutzers in Bezug auf die Organisation', max_length=2, verbose_name='Rolle')),
                ('editing_note', models.TextField(help_text='Begründung für die Ablehnung des Antrags bzw. Hinweise zur Freigabe - wie wurde Antragsteller kontaktiert/geprüft. Bei Ablehnung bekommt der Antragsteller die Begründung als Mail zugestellt!', null=True, verbose_name='Begründung')),
                ('organizations', models.ManyToManyField(related_name='pending_role_requests', to='xplanung_light.administrativeorganization', verbose_name='Gebietskörperschaft(en)')),
                ('owned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRequestForRole_organizations',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('administrativeorganization', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.administrativeorganization')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='xplanung_light.historicalrequestforrole')),
                ('requestforrole', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.requestforrole')),
            ],
            options={
                'verbose_name': 'HistoricalRequestForRole_organizations',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
