# Generated by Django 4.2.21 on 2026-06-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0083_historicalrequestforrole_requestforrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequestfororganizationadmin_organizations',
            name='administrativeorganization',
        ),
        migrations.RemoveField(
            model_name='historicalrequestfororganizationadmin_organizations',
            name='history',
        ),
        migrations.RemoveField(
            model_name='historicalrequestfororganizationadmin_organizations',
            name='requestfororganizationadmin',
        ),
        migrations.RemoveField(
            model_name='requestfororganizationadmin',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='requestfororganizationadmin',
            name='owned_by_user',
        ),
        migrations.DeleteModel(
            name='HistoricalRequestForOrganizationAdmin',
        ),
        migrations.DeleteModel(
            name='HistoricalRequestForOrganizationAdmin_organizations',
        ),
        migrations.DeleteModel(
            name='RequestForOrganizationAdmin',
        ),
    ]
