# Generated by Django 4.2.21 on 2026-06-26 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0084_remove_historicalrequestfororganizationadmin_organizations_administrativeorganization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanbeteiligungbeitrag',
            name='eingangsdatum',
            field=models.DateField(default=django.utils.timezone.now, help_text='Eingangsdatum des Beitrags.', verbose_name='Eingangsdatum'),
        ),
        migrations.AddField(
            model_name='fplanbeteiligungbeitrag',
            name='eingangsdatum',
            field=models.DateField(default=django.utils.timezone.now, help_text='Eingangsdatum des Beitrags.', verbose_name='Eingangsdatum'),
        ),
        migrations.AddField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='eingangsdatum',
            field=models.DateField(default=django.utils.timezone.now, help_text='Eingangsdatum des Beitrags.', verbose_name='Eingangsdatum'),
        ),
        migrations.AddField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='eingangsdatum',
            field=models.DateField(default=django.utils.timezone.now, help_text='Eingangsdatum des Beitrags.', verbose_name='Eingangsdatum'),
        ),
    ]
