# Generated by Django 4.2.21 on 2026-06-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0085_bplanbeteiligungbeitrag_eingangsdatum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bplanbeteiligungbeitrag',
            name='eingangsdatum',
            field=models.DateField(help_text='Eingangsdatum des Beitrags.', verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='fplanbeteiligungbeitrag',
            name='eingangsdatum',
            field=models.DateField(help_text='Eingangsdatum des Beitrags.', verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='historicalbplanbeteiligungbeitrag',
            name='eingangsdatum',
            field=models.DateField(help_text='Eingangsdatum des Beitrags.', verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='historicalfplanbeteiligungbeitrag',
            name='eingangsdatum',
            field=models.DateField(help_text='Eingangsdatum des Beitrags.', verbose_name='Eingangsdatum'),
        ),
    ]
