# Generated by Django 4.2.21 on 2026-06-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplanung_light', '0086_alter_bplanbeteiligungbeitrag_eingangsdatum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bplanspezexternereferenz',
            name='public',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Informationen über die frei verfügbaren Schnittstellen publiziert werden (Links in Detail-Ansicht, ZIP-Archiv, ...).', verbose_name='Anlage öffentlich verfügbar'),
        ),
        migrations.AddField(
            model_name='fplanspezexternereferenz',
            name='public',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Informationen über die frei verfügbaren Schnittstellen publiziert werden (Links in Detail-Ansicht, ZIP-Archiv, ...).', verbose_name='Anlage öffentlich verfügbar'),
        ),
        migrations.AddField(
            model_name='historicalbplanspezexternereferenz',
            name='public',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Informationen über die frei verfügbaren Schnittstellen publiziert werden (Links in Detail-Ansicht, ZIP-Archiv, ...).', verbose_name='Anlage öffentlich verfügbar'),
        ),
        migrations.AddField(
            model_name='historicalfplanspezexternereferenz',
            name='public',
            field=models.BooleanField(default=False, help_text='Gibt an, ob Informationen über die frei verfügbaren Schnittstellen publiziert werden (Links in Detail-Ansicht, ZIP-Archiv, ...).', verbose_name='Anlage öffentlich verfügbar'),
        ),
    ]
