# Generated by Django 4.2.21 on 2026-09-10 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_clamd.validators
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xplanung_light', '0089_alter_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactedFPlanBeteiligungBeitragAnhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('attachment', models.FileField(max_length=1024, upload_to='uploads', validators=[django_clamd.validators.validate_file_infection], verbose_name='Geschwärzte Version des Dokuments')),
                ('anhang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redacted_version', to='xplanung_light.fplanbeteiligungbeitraganhang', verbose_name='Anhang')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedactedBPlanBeteiligungBeitragAnhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('attachment', models.FileField(max_length=1024, upload_to='uploads', validators=[django_clamd.validators.validate_file_infection], verbose_name='Geschwärzte Version des Dokuments')),
                ('anhang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redacted_version', to='xplanung_light.bplanbeteiligungbeitraganhang', verbose_name='Anhang')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalRedactedFPlanBeteiligungBeitragAnhang',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('attachment', models.TextField(max_length=1024, validators=[django_clamd.validators.validate_file_infection], verbose_name='Geschwärzte Version des Dokuments')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anhang', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.fplanbeteiligungbeitraganhang', verbose_name='Anhang')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical redacted f plan beteiligung beitrag anhang',
                'verbose_name_plural': 'historical redacted f plan beteiligung beitrag anhangs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRedactedBPlanBeteiligungBeitragAnhang',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('attachment', models.TextField(max_length=1024, validators=[django_clamd.validators.validate_file_infection], verbose_name='Geschwärzte Version des Dokuments')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anhang', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='xplanung_light.bplanbeteiligungbeitraganhang', verbose_name='Anhang')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical redacted b plan beteiligung beitrag anhang',
                'verbose_name_plural': 'historical redacted b plan beteiligung beitrag anhangs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
