# Generated by Django 4.2.21 on 2026-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xplanung_light", "0090_redactedfplanbeteiligungbeitraganhang_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bplan",
            index=models.Index(fields=["public"], name="xplanung_li_public_e6ffb5_idx"),
        ),
        migrations.AddIndex(
            model_name="bplan",
            index=models.Index(
                fields=["inkrafttretens_datum"], name="xplanung_li_inkraft_e38a5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bplan",
            index=models.Index(
                fields=["untergangs_datum"], name="xplanung_li_unterga_2f9f18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bplanbeteiligung",
            index=models.Index(
                fields=["bekanntmachung_datum"], name="xplanung_li_bekannt_59a9ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bplanbeteiligung",
            index=models.Index(
                fields=["start_datum"], name="xplanung_li_start_d_65cc1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bplanbeteiligung",
            index=models.Index(
                fields=["end_datum"], name="xplanung_li_end_dat_b4a2d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fplan",
            index=models.Index(fields=["public"], name="xplanung_li_public_9ca7eb_idx"),
        ),
        migrations.AddIndex(
            model_name="fplan",
            index=models.Index(
                fields=["wirksamkeits_datum"], name="xplanung_li_wirksam_7d415b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fplan",
            index=models.Index(
                fields=["untergangs_datum"], name="xplanung_li_unterga_1d5ef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fplanbeteiligung",
            index=models.Index(
                fields=["bekanntmachung_datum"], name="xplanung_li_bekannt_b6b37b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fplanbeteiligung",
            index=models.Index(
                fields=["start_datum"], name="xplanung_li_start_d_57cb83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fplanbeteiligung",
            index=models.Index(
                fields=["end_datum"], name="xplanung_li_end_dat_dacb2b_idx"
            ),
        ),
    ]
